/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_wallpaper_with_a_simple_graphic_of_a_robot_arm_aga_c5c5f8df_6b84_4c2d_a94d_71c70b1a0fac_0_1 from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_robot_arm_aga_c5c5f8df-6b84-4c2d-a94d-71c70b1a0fac-0_1.png';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_robot_arm_aga_c5c5f8df-6b84-4c2d-a94d-71c70b1a0fac-0_1.json';
import { IWallpaperComponent } from '../IWallpaperComponent';

/**
 * Image of a wallpaper with a simple graphic of a robot arm aga c5c5f8df-6b84-4c2d-a94d-71c70b1a0fac-0
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithASimpleGraphicOfARobotArmAgaC5c5f8df6b844c2dA94d71c70b1a0fac0_1_Image() {
    return (
        <Image
            alt="a wallpaper with a simple graphic of a robot arm aga c5c5f8df-6b84-4c2d-a94d-71c70b1a0fac-0"
            src={a_wallpaper_with_a_simple_graphic_of_a_robot_arm_aga_c5c5f8df_6b84_4c2d_a94d_71c70b1a0fac_0_1}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperWithASimpleGraphicOfARobotArmAgaC5c5f8df6b844c2dA94d71c70b1a0fac0_1_Image.metadata =
    metadata satisfies IWallpaperComponent;
