/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_photograph_of_a_desert_landscape_at_night_with_the_93e80a95_d8f5_4556_9324_b10f8d61dee5_0_1 from './Pavol_Hejn_a_photograph_of_a_desert_landscape_at_night_with_the_93e80a95-d8f5-4556-9324-b10f8d61dee5-0_1.png';
import metadata from './Pavol_Hejn_a_photograph_of_a_desert_landscape_at_night_with_the_93e80a95-d8f5-4556-9324-b10f8d61dee5-0_1.json';
import { IWallpaperComponent } from '../IWallpaperComponent';

/**
 * Image of a photograph of a desert landscape at night with the 93e80a95-d8f5-4556-9324-b10f8d61dee5-0
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function APhotographOfADesertLandscapeAtNightWithThe93e80a95D8f545569324B10f8d61dee50_1_Image() {
    return (
        <Image
            alt="a photograph of a desert landscape at night with the 93e80a95-d8f5-4556-9324-b10f8d61dee5-0"
            src={a_photograph_of_a_desert_landscape_at_night_with_the_93e80a95_d8f5_4556_9324_b10f8d61dee5_0_1}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

APhotographOfADesertLandscapeAtNightWithThe93e80a95D8f545569324B10f8d61dee50_1_Image.metadata =
    metadata satisfies IWallpaperComponent;
