/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import an_abstract_wallpaper_inspired_by_the_shapes_and_col28d25e0_9687_43a2_aeb7_17a3b30b0362_0_0_0 from './Pavol_Hejn_an_abstract_wallpaper_inspired_by_the_shapes_and_col_028d25e0-9687-43a2-aeb7-17a3b30b0362-0_0.png';
import metadata from './Pavol_Hejn_an_abstract_wallpaper_inspired_by_the_shapes_and_col_028d25e0-9687-43a2-aeb7-17a3b30b0362-0_0.json';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import { IImageColorStats } from '../../../../src/utils/image/computeImageColorStats';
import { Color } from '../../../../src/utils/color/Color';

/**
 * Image of an abstract wallpaper inspired by the shapes and col28d25e0-9687-43a2-aeb7-17a3b30b0362-0 0
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AnAbstractWallpaperInspiredByTheShapesAndCol28d25e0968743a2Aeb717a3b30b036200_0_Image() {
    return (
        <Image
            alt="an abstract wallpaper inspired by the shapes and col28d25e0-9687-43a2-aeb7-17a3b30b0362-0 0"
            src={an_abstract_wallpaper_inspired_by_the_shapes_and_col28d25e0_9687_43a2_aeb7_17a3b30b0362_0_0_0}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AnAbstractWallpaperInspiredByTheShapesAndCol28d25e0968743a2Aeb717a3b30b036200_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnAbstractWallpaperInspiredByTheShapesAndCol28d25e0968743a2Aeb717a3b30b036200_0_Image.colorStats = {
    averageColor: Color.fromHex('#34362f'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    mostFrequentColor: Color.fromHex('#081315'),
    leastFrequentColor: Color.fromHex('#220a14'),
} satisfies IImageColorStats;
