/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_repeating_pattern_of_neon_colored_391ec65a-a091-4d76-9e42-d16de5b0c620-0_0.json';
import source from './Pavol_Hejn_a_wallpaper_with_a_repeating_pattern_of_neon_colored_391ec65a-a091-4d76-9e42-d16de5b0c620-0_0.png';

/**
 * Image of A wallpaper with a repeating pattern of neon-colored circuitry, set against a black background.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithARepeatingPatternOfNeonColored391ec65aA0914d769e42D16de5b0c6200_0_Image() {
    return (
        <Image
            alt="A wallpaper with a repeating pattern of neon-colored circuitry, set against a black background."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperWithARepeatingPatternOfNeonColored391ec65aA0914d769e42D16de5b0c6200_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperWithARepeatingPatternOfNeonColored391ec65aA0914d769e42D16de5b0c6200_0_Image.colorStats = {
    averageColor: Color.fromHex('#101115'),
    lightestColor: Color.fromHex('#f8ffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#f8ffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#bf3945'), Color.fromHex('#3afeff')],
    minmaxGreen: [Color.fromHex('#28bd3f'), Color.fromHex('#e059fb')],
    minmaxBlue: [Color.fromHex('#1824b5'), Color.fromHex('#f2f885')],
    mostFrequentColor: Color.fromHex('#000000'),
    mostSaturatedColor: Color.fromHex('#000100'),
    mostGroupedColor: Color.fromHex('#000000'),
    bottom: {
        averageColor: Color.fromHex('#0c090e'),
        lightestColor: Color.fromHex('#9e91d9'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#d5fda5'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#c2512a'), Color.fromHex('#00b6fe')],
        minmaxGreen: [Color.fromHex('#409e47'), Color.fromHex('#6a36d9')],
        minmaxBlue: [Color.fromHex('#292ab3'), Color.fromHex('#d0fe98')],
        mostFrequentColor: Color.fromHex('#000000'),
        mostSaturatedColor: Color.fromHex('#000101'),
        mostGroupedColor: Color.fromHex('#000000'),
    },
} satisfies IImageColorStats;
