/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_abstract_watercolor_painting_with_vibrant_colors__d1f72b89-0604-443b-95fe-822318ac0437-0_3.json';
import source from './Pavol_Hejn_an_abstract_watercolor_painting_with_vibrant_colors__d1f72b89-0604-443b-95fe-822318ac0437-0_3.png';

/**
 * Image of An abstract watercolor painting with vibrant colors for an art or design blog
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AnAbstractWatercolorPaintingWithVibrantColorsD1f72b890604443b95fe822318ac04370_3_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="An abstract watercolor painting with vibrant colors for an art or design blog"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AnAbstractWatercolorPaintingWithVibrantColorsD1f72b890604443b95fe822318ac04370_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnAbstractWatercolorPaintingWithVibrantColorsD1f72b890604443b95fe822318ac04370_3_Image.colorStats = {
    averageColor: Color.fromHex('#aaa4a2'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#774411'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000033')],
    minmaxRed: [Color.fromHex('#dd2211'), Color.fromHex('#ccffff')],
    minmaxGreen: [Color.fromHex('#44aa55'), Color.fromHex('#ffccff')],
    minmaxBlue: [Color.fromHex('#1144aa'), Color.fromHex('#ffcc33')],
    mostFrequentColor: Color.fromHex('#eeaa88'),
    mostSaturatedColor: Color.fromHex('#003377'),
    mostGroupedColor: Color.fromHex('#aaaacc'),
    bottom: {
        averageColor: Color.fromHex('#a9a5a7'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#bb2200'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000033')],
        minmaxRed: [Color.fromHex('#dd2211'), Color.fromHex('#ccffff')],
        minmaxGreen: [Color.fromHex('#88bb66'), Color.fromHex('#ffddff')],
        minmaxBlue: [Color.fromHex('#1144aa'), Color.fromHex('#ffcc33')],
        mostFrequentColor: Color.fromHex('#eeaa88'),
        mostSaturatedColor: Color.fromHex('#003388'),
        mostGroupedColor: Color.fromHex('#eeccaa'),
    },
} satisfies IImageColorStats;
