/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_repeating_pattern_of_abstract_geo_a0dd2025-1474-4a3c-a8a5-d8b09639714f-0_1.json';
import source from './Pavol_Hejn_a_wallpaper_with_a_repeating_pattern_of_abstract_geo_a0dd2025-1474-4a3c-a8a5-d8b09639714f-0_1.png';

/**
 * Image of A wallpaper with a repeating pattern of abstract geometric shapes and patterns, inspired by web design trends and color schemes.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithARepeatingPatternOfAbstractGeoA0dd202514744a3cA8a5D8b09639714f0_1_Image() {
    return (
        <Image
            alt="A wallpaper with a repeating pattern of abstract geometric shapes and patterns, inspired by web design trends and color schemes."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperWithARepeatingPatternOfAbstractGeoA0dd202514744a3cA8a5D8b09639714f0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperWithARepeatingPatternOfAbstractGeoA0dd202514744a3cA8a5D8b09639714f0_1_Image.colorStats = {
    averageColor: Color.fromHex('#876a5a'),
    lightestColor: Color.fromHex('#eeddbb'),
    darkestColor: Color.fromHex('#111111'),
    minmaxWhite: [Color.fromHex('#eeddbb'), Color.fromHex('#111111')],
    minmaxRed: [Color.fromHex('#cc3322'), Color.fromHex('#99ccbb')],
    minmaxGreen: [Color.fromHex('#228866'), Color.fromHex('#ee5555')],
    minmaxBlue: [Color.fromHex('#226677'), Color.fromHex('#ffddaa')],
    mostFrequentColor: Color.fromHex('#888866'),
    mostSaturatedColor: Color.fromHex('#330011'),
    mostGroupedColor: Color.fromHex('#332222'),
    bottom: {
        averageColor: Color.fromHex('#846858'),
        lightestColor: Color.fromHex('#eeddbb'),
        darkestColor: Color.fromHex('#221111'),
        minmaxWhite: [Color.fromHex('#eeddbb'), Color.fromHex('#111122')],
        minmaxRed: [Color.fromHex('#cc4444'), Color.fromHex('#eeddbb')],
        minmaxGreen: [Color.fromHex('#449977'), Color.fromHex('#dd5555')],
        minmaxBlue: [Color.fromHex('#334466'), Color.fromHex('#ffcc99')],
        mostFrequentColor: Color.fromHex('#888866'),
        mostSaturatedColor: Color.fromHex('#116666'),
        mostGroupedColor: Color.fromHex('#332222'),
    },
} satisfies IImageColorStats;
