/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_illustration_of_a_futuristic_space_elevator_with__3e684cfa-2ecc-4a82-8854-f3a0136b3f78-0_0.json';
import source from './Pavol_Hejn_an_illustration_of_a_futuristic_space_elevator_with__3e684cfa-2ecc-4a82-8854-f3a0136b3f78-0_0.png';

/**
 * Image of An illustration of a futuristic space elevator, with a cable stretching from Earth into orbit.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AnIllustrationOfAFuturisticSpaceElevatorWith3e684cfa2ecc4a828854F3a0136b3f780_0_Image() {
    return (
        <Image
            alt="An illustration of a futuristic space elevator, with a cable stretching from Earth into orbit."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AnIllustrationOfAFuturisticSpaceElevatorWith3e684cfa2ecc4a828854F3a0136b3f780_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnIllustrationOfAFuturisticSpaceElevatorWith3e684cfa2ecc4a828854F3a0136b3f780_0_Image.colorStats = {
    averageColor: Color.fromHex('#505f73'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#080000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#010003')],
    minmaxRed: [Color.fromHex('#834b3a'), Color.fromHex('#f3ffff')],
    minmaxGreen: [Color.fromHex('#5e7374'), Color.fromHex('#fffdff')],
    minmaxBlue: [Color.fromHex('#346094'), Color.fromHex('#ffffed')],
    mostFrequentColor: Color.fromHex('#102138'),
    mostSaturatedColor: Color.fromHex('#040008'),
    mostGroupedColor: Color.fromHex('#091c32'),
    bottom: {
        averageColor: Color.fromHex('#2b394f'),
        lightestColor: Color.fromHex('#fffcf4'),
        darkestColor: Color.fromHex('#080000'),
        minmaxWhite: [Color.fromHex('#fffcf4'), Color.fromHex('#010003')],
        minmaxRed: [Color.fromHex('#834b3a'), Color.fromHex('#fffef0')],
        minmaxGreen: [Color.fromHex('#6b7674'), Color.fromHex('#fffcf4')],
        minmaxBlue: [Color.fromHex('#3e5a86'), Color.fromHex('#ffffed')],
        mostFrequentColor: Color.fromHex('#102138'),
        mostSaturatedColor: Color.fromHex('#040008'),
        mostGroupedColor: Color.fromHex('#253853'),
    },
} satisfies IImageColorStats;
