/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_digital_landscape_with_geometric_shapes_and_neon_c_e41c5a45-70e4-41aa-be2c-290f518aa5f7-0_2.json';
import source from './Pavol_Hejn_a_digital_landscape_with_geometric_shapes_and_neon_c_e41c5a45-70e4-41aa-be2c-290f518aa5f7-0_2.png';

/**
 * Image of A digital landscape with geometric shapes and neon colors
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function ADigitalLandscapeWithGeometricShapesAndNeonCE41c5a4570e441aaBe2c290f518aa5f70_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A digital landscape with geometric shapes and neon colors"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ADigitalLandscapeWithGeometricShapesAndNeonCE41c5a4570e441aaBe2c290f518aa5f70_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ADigitalLandscapeWithGeometricShapesAndNeonCE41c5a4570e441aaBe2c290f518aa5f70_2_Image.colorStats = {
    averageColor: Color.fromHex('#5f2557'),
    lightestColor: Color.fromHex('#ff22dd'),
    darkestColor: Color.fromHex('#111111'),
    minmaxWhite: [Color.fromHex('#eeccaa'), Color.fromHex('#000033')],
    minmaxRed: [Color.fromHex('#dd1111'), Color.fromHex('#00ffff')],
    minmaxGreen: [Color.fromHex('#00aa99'), Color.fromHex('#ff11cc')],
    minmaxBlue: [Color.fromHex('#3311cc'), Color.fromHex('#ffcc88')],
    mostFrequentColor: Color.fromHex('#001133'),
    mostSaturatedColor: Color.fromHex('#002244'),
    mostGroupedColor: Color.fromHex('#002233'),
    bottom: {
        averageColor: Color.fromHex('#2c1d61'),
        lightestColor: Color.fromHex('#ff22dd'),
        darkestColor: Color.fromHex('#111111'),
        minmaxWhite: [Color.fromHex('#77bbee'), Color.fromHex('#000033')],
        minmaxRed: [Color.fromHex('#dd0033'), Color.fromHex('#00ffff')],
        minmaxGreen: [Color.fromHex('#00aa99'), Color.fromHex('#ff11cc')],
        minmaxBlue: [Color.fromHex('#3311cc'), Color.fromHex('#00ffdd')],
        mostFrequentColor: Color.fromHex('#001133'),
        mostSaturatedColor: Color.fromHex('#aa0077'),
        mostGroupedColor: Color.fromHex('#001133'),
    },
} satisfies IImageColorStats;
