/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__a687fcef-5657-4e8b-8a37-e7839d797d0e-0_0.json';
import source from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__a687fcef-5657-4e8b-8a37-e7839d797d0e-0_0.png';

/**
 * Image of A photograph of a meteor shower, with bright streaks of light crossing the night sky.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function APhotographOfAMeteorShowerWithBrightStreaksA687fcef56574e8b8a37E7839d797d0e0_0_Image() {
    return (
        <Image
            alt="A photograph of a meteor shower, with bright streaks of light crossing the night sky."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

APhotographOfAMeteorShowerWithBrightStreaksA687fcef56574e8b8a37E7839d797d0e0_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
APhotographOfAMeteorShowerWithBrightStreaksA687fcef56574e8b8a37E7839d797d0e0_0_Image.colorStats = {
    averageColor: Color.fromHex('#3f302f'),
    lightestColor: Color.fromHex('#f8f1fd'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#fbf3fb'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#a0440b'), Color.fromHex('#f6f5f7')],
    minmaxGreen: [Color.fromHex('#847359'), Color.fromHex('#fbf3fb')],
    minmaxBlue: [Color.fromHex('#5d4e63'), Color.fromHex('#fff5ec')],
    mostFrequentColor: Color.fromHex('#010307'),
    mostSaturatedColor: Color.fromHex('#06000a'),
    mostGroupedColor: Color.fromHex('#05060b'),
    bottom: {
        averageColor: Color.fromHex('#4a322a'),
        lightestColor: Color.fromHex('#f3e6eb'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#f6e7ea'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#a0440b'), Color.fromHex('#f6e7ea')],
        minmaxGreen: [Color.fromHex('#847359'), Color.fromHex('#fce7e6')],
        minmaxBlue: [Color.fromHex('#4f4f52'), Color.fromHex('#ffe6ab')],
        mostFrequentColor: Color.fromHex('#010307'),
        mostSaturatedColor: Color.fromHex('#00030e'),
        mostGroupedColor: Color.fromHex('#05060b'),
    },
} satisfies IImageColorStats;
