/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/computeImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_blue_whale_as_favicon_41f877b6-57e1-4958-a536-5b78de6b22fb-0_0.json';
import source from './Pavol_Hejn_blue_whale_as_favicon_41f877b6-57e1-4958-a536-5b78de6b22fb-0_0.png';

/**
 * Image of Blue whale as favicon
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function BlueWhaleAsFavicon41f877b657e14958A5365b78de6b22fb0_0_Image() {
    return (
        <Image
            alt="Blue whale as favicon"
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

BlueWhaleAsFavicon41f877b657e14958A5365b78de6b22fb0_0_Image.metadata = metadata satisfies IWallpaperMetadata;
BlueWhaleAsFavicon41f877b657e14958A5365b78de6b22fb0_0_Image.colorStats = {
    averageColor: Color.fromHex('#b5d4e3'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000720'),
    mostFrequentColor: Color.fromHex('#fffffe'),
    leastFrequentColor: Color.fromHex('#fefcfe'),
} satisfies IImageColorStats;
