/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import metadata from './Pavol_Hejn_a_minimalist_wallpaper_with_a_single_line_drawing_of_3d15429c-3bc5-41d1-984f-e15e14713029-0_0.json';
import a_minimalist_wallpaper_with_a_single_line_drawing_of_3d15429c_3bc5_41d1_984f_e15e14713029_0_0 from './Pavol_Hejn_a_minimalist_wallpaper_with_a_single_line_drawing_of_3d15429c-3bc5-41d1-984f-e15e14713029-0_0.png';

/**
 * Image of a minimalist wallpaper with a single line drawing of 3d15429c-3bc5-41d1-984f-e15e14713029-0
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AMinimalistWallpaperWithASingleLineDrawingOf3d15429c3bc541d1984fE15e147130290_0_Image() {
    return (
        <Image
            alt="a minimalist wallpaper with a single line drawing of 3d15429c-3bc5-41d1-984f-e15e14713029-0"
            src={a_minimalist_wallpaper_with_a_single_line_drawing_of_3d15429c_3bc5_41d1_984f_e15e14713029_0_0}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AMinimalistWallpaperWithASingleLineDrawingOf3d15429c3bc541d1984fE15e147130290_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AMinimalistWallpaperWithASingleLineDrawingOf3d15429c3bc541d1984fE15e147130290_0_Image.colorStats = {
    averageColor: Color.fromHex('#b35d55'),
    lightestColor: Color.fromHex('#fffde3'),
    darkestColor: Color.fromHex('#2b0000'),
    mostFrequentColor: Color.fromHex('#e94630'),
    leastFrequentColor: Color.fromHex('#c6433c'),
} satisfies IImageColorStats;
