/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_minimalist_wallpaper_with_a_single_line_drawing_of_6839d413-4e56-4470-81cf-737ac57a5d6c-0_1.json';
import source from './Pavol_Hejn_a_minimalist_wallpaper_with_a_single_line_drawing_of_6839d413-4e56-4470-81cf-737ac57a5d6c-0_1.png';

/**
 * Image of A minimalist wallpaper with a single line drawing of a cyborg, in a striking color such as bright red or blue.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AMinimalistWallpaperWithASingleLineDrawingOf6839d4134e56447081cf737ac57a5d6c0_1_Image() {
    return (
        <Image
            alt="A minimalist wallpaper with a single line drawing of a cyborg, in a striking color such as bright red or blue."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AMinimalistWallpaperWithASingleLineDrawingOf6839d4134e56447081cf737ac57a5d6c0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AMinimalistWallpaperWithASingleLineDrawingOf6839d4134e56447081cf737ac57a5d6c0_1_Image.colorStats = {
    averageColor: Color.fromHex('#ba615e'),
    lightestColor: Color.fromHex('#e7f5ff'),
    darkestColor: Color.fromHex('#590a00'),
    minmaxWhite: [Color.fromHex('#e7f5ff'), Color.fromHex('#3c0009')],
    minmaxRed: [Color.fromHex('#fb0d02'), Color.fromHex('#5ffbff')],
    minmaxGreen: [Color.fromHex('#2da990'), Color.fromHex('#fb0d02')],
    minmaxBlue: [Color.fromHex('#005da4'), Color.fromHex('#fff2dd')],
    mostFrequentColor: Color.fromHex('#df5d46'),
    mostSaturatedColor: Color.fromHex('#630007'),
    mostGroupedColor: Color.fromHex('#ef4f3f'),
    bottom: {
        averageColor: Color.fromHex('#ad6a6a'),
        lightestColor: Color.fromHex('#e7f5ff'),
        darkestColor: Color.fromHex('#5b1e00'),
        minmaxWhite: [Color.fromHex('#e7f5ff'), Color.fromHex('#3c0009')],
        minmaxRed: [Color.fromHex('#e7150d'), Color.fromHex('#3fe8ff')],
        minmaxGreen: [Color.fromHex('#24bda1'), Color.fromHex('#d30018')],
        minmaxBlue: [Color.fromHex('#005da4'), Color.fromHex('#ffeccd')],
        mostFrequentColor: Color.fromHex('#df5d46'),
        mostSaturatedColor: Color.fromHex('#630007'),
        mostGroupedColor: Color.fromHex('#e64739'),
    },
} satisfies IImageColorStats;
