/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_featuring_a_repeating_pattern_of_sleek_a_596c7836-b10d-4d28-aa0b-fdfe1d0fb815-0_0.json';
import source from './Pavol_Hejn_a_wallpaper_featuring_a_repeating_pattern_of_sleek_a_596c7836-b10d-4d28-aa0b-fdfe1d0fb815-0_0.png';

/**
 * Image of A wallpaper featuring a repeating pattern of sleek and modern digital devices, such as smartphones, tablets, and laptops.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AWallpaperFeaturingARepeatingPatternOfSleekA596c7836B10d4d28Aa0bFdfe1d0fb8150_0_Image() {
    return (
        <Image
            alt="A wallpaper featuring a repeating pattern of sleek and modern digital devices, such as smartphones, tablets, and laptops."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperFeaturingARepeatingPatternOfSleekA596c7836B10d4d28Aa0bFdfe1d0fb8150_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperFeaturingARepeatingPatternOfSleekA596c7836B10d4d28Aa0bFdfe1d0fb8150_0_Image.colorStats = {
    averageColor: Color.fromHex('#727578'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#4a4144'), Color.fromHex('#f2ffff')],
    minmaxGreen: [Color.fromHex('#5f7571'), Color.fromHex('#fffcff')],
    minmaxBlue: [Color.fromHex('#4a5963'), Color.fromHex('#fffffa')],
    mostFrequentColor: Color.fromHex('#5f6f74'),
    mostSaturatedColor: Color.fromHex('#000a01'),
    mostGroupedColor: Color.fromHex('#171c1f'),
    bottom: {
        averageColor: Color.fromHex('#797c7f'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#4f4849'), Color.fromHex('#fdffff')],
        minmaxGreen: [Color.fromHex('#5f7571'), Color.fromHex('#fffeff')],
        minmaxBlue: [Color.fromHex('#4d5963'), Color.fromHex('#ffffff')],
        mostFrequentColor: Color.fromHex('#5f6f74'),
        mostSaturatedColor: Color.fromHex('#000505'),
        mostGroupedColor: Color.fromHex('#171c1f'),
    },
} satisfies IImageColorStats;
