/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_team_of_ainauts_piloting_a_small_spacecraft_throug_bdbfc142_36bb_455b_aeac_e31744cd233b_0_1 from './Pavol_Hejn_a_team_of_ainauts_piloting_a_small_spacecraft_throug_bdbfc142-36bb-455b-aeac-e31744cd233b-0_1.png';
import metadata from './Pavol_Hejn_a_team_of_ainauts_piloting_a_small_spacecraft_throug_bdbfc142-36bb-455b-aeac-e31744cd233b-0_1.json';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import { IImageColorStats } from '../../../../src/utils/image/computeImageColorStats';
import { Color } from '../../../../src/utils/color/Color';

/**
 * Image of a team of ainauts piloting a small spacecraft throug bdbfc142-36bb-455b-aeac-e31744cd233b-0
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ATeamOfAinautsPilotingASmallSpacecraftThrougBdbfc14236bb455bAeacE31744cd233b0_1_Image() {
    return (
        <Image
            alt="a team of ainauts piloting a small spacecraft throug bdbfc142-36bb-455b-aeac-e31744cd233b-0"
            src={a_team_of_ainauts_piloting_a_small_spacecraft_throug_bdbfc142_36bb_455b_aeac_e31744cd233b_0_1}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ATeamOfAinautsPilotingASmallSpacecraftThrougBdbfc14236bb455bAeacE31744cd233b0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ATeamOfAinautsPilotingASmallSpacecraftThrougBdbfc14236bb455bAeacE31744cd233b0_1_Image.colorStats = {
    averageColor: Color.fromHex('#37353c'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    mostFrequentColor: Color.fromHex('#090a10'),
    leastFrequentColor: Color.fromHex('#303535'),
} satisfies IImageColorStats;
