/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_black_and_white_outline_of_an_astronaut_exploring_7a578961_dd71_40d5_83d9_07b59a895d39_0_0 from './Pavol_Hejn_a_black_and_white_outline_of_an_astronaut_exploring__7a578961-dd71-40d5-83d9-07b59a895d39-0_0.png';
import metadata from './Pavol_Hejn_a_black_and_white_outline_of_an_astronaut_exploring__7a578961-dd71-40d5-83d9-07b59a895d39-0_0.json';
import { IWallpaperMetadata } from '../IWallpaperComponent';

/**
 * Image of a black and white outline of an astronaut exploring  7a578961-dd71-40d5-83d9-07b59a895d39-0
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function ABlackAndWhiteOutlineOfAnAstronautExploring7a578961Dd7140d583d907b59a895d390_0_Image() {
    return (
        <Image
            alt="a black and white outline of an astronaut exploring  7a578961-dd71-40d5-83d9-07b59a895d39-0"
            src={a_black_and_white_outline_of_an_astronaut_exploring_7a578961_dd71_40d5_83d9_07b59a895d39_0_0}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ABlackAndWhiteOutlineOfAnAstronautExploring7a578961Dd7140d583d907b59a895d390_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
