/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_photograph_of_a_mountain_range_on_another_planet_w_888a4d10-c1bb-40dc-8bb0-234ffb78f253-0_2.json';
import source from './Pavol_Hejn_a_photograph_of_a_mountain_range_on_another_planet_w_888a4d10-c1bb-40dc-8bb0-234ffb78f253-0_2.png';

/**
 * Image of A photograph of a mountain range on another planet, with the bright sun shining through the peaks.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function APhotographOfAMountainRangeOnAnotherPlanetW888a4d10C1bb40dc8bb0234ffb78f2530_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A photograph of a mountain range on another planet, with the bright sun shining through the peaks."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

APhotographOfAMountainRangeOnAnotherPlanetW888a4d10C1bb40dc8bb0234ffb78f2530_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
APhotographOfAMountainRangeOnAnotherPlanetW888a4d10C1bb40dc8bb0234ffb78f2530_2_Image.colorStats = {
    averageColor: Color.fromHex('#7c5d4f'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#993300'), Color.fromHex('#ffffff')],
    minmaxGreen: [Color.fromHex('#888866'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#445577'), Color.fromHex('#ffffdd')],
    mostFrequentColor: Color.fromHex('#442211'),
    mostSaturatedColor: Color.fromHex('#110000'),
    mostGroupedColor: Color.fromHex('#ffffee'),
    bottom: {
        averageColor: Color.fromHex('#522d20'),
        lightestColor: Color.fromHex('#ffffdd'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffdd'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#993300'), Color.fromHex('#ffffdd')],
        minmaxGreen: [Color.fromHex('#888866'), Color.fromHex('#ffffdd')],
        minmaxBlue: [Color.fromHex('#444455'), Color.fromHex('#ffffdd')],
        mostFrequentColor: Color.fromHex('#442211'),
        mostSaturatedColor: Color.fromHex('#221100'),
        mostGroupedColor: Color.fromHex('#221111'),
    },
} satisfies IImageColorStats;
