/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_dreamy_forest_scene_with_fairies_380486d5-af02-4d6b-ae31-e4f04a6c3580-0_2.json';
import source from './Pavol_Hejn_a_dreamy_forest_scene_with_fairies_380486d5-af02-4d6b-ae31-e4f04a6c3580-0_2.png';

/**
 * Image of A dreamy forest scene with fairies
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function ADreamyForestSceneWithFairies380486d5Af024d6bAe31E4f04a6c35800_2_Image() {
    return (
        <Image
            alt="A dreamy forest scene with fairies"
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ADreamyForestSceneWithFairies380486d5Af024d6bAe31E4f04a6c35800_2_Image.metadata = metadata satisfies IWallpaperMetadata;
ADreamyForestSceneWithFairies380486d5Af024d6bAe31E4f04a6c35800_2_Image.colorStats = {
    averageColor: Color.fromHex('#595842'),
    lightestColor: Color.fromHex('#fffdff'),
    darkestColor: Color.fromHex('#000100'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#ad3a14'), Color.fromHex('#ffffff')],
    minmaxGreen: [Color.fromHex('#77923d'), Color.fromHex('#fffdff')],
    minmaxBlue: [Color.fromHex('#4b3d83'), Color.fromHex('#ffff68')],
    mostFrequentColor: Color.fromHex('#051314'),
    mostSaturatedColor: Color.fromHex('#000606'),
    mostGroupedColor: Color.fromHex('#0f1009'),
    bottom: {
        averageColor: Color.fromHex('#383923'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000100'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#ad3a14'), Color.fromHex('#ffffff')],
        minmaxGreen: [Color.fromHex('#77923d'), Color.fromHex('#ffffff')],
        minmaxBlue: [Color.fromHex('#4b3d83'), Color.fromHex('#ffff68')],
        mostFrequentColor: Color.fromHex('#051314'),
        mostSaturatedColor: Color.fromHex('#000606'),
        mostGroupedColor: Color.fromHex('#0f1009'),
    },
} satisfies IImageColorStats;
