/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_illustration_of_a_robotic_explorer_with_metallic__ed76f6f9-6722-4c45-8c69-9918c688c779-0_2.json';
import source from './Pavol_Hejn_an_illustration_of_a_robotic_explorer_with_metallic__ed76f6f9-6722-4c45-8c69-9918c688c779-0_2.png';

/**
 * Image of An illustration of a robotic explorer, with metallic textures and intricate details.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AnIllustrationOfARoboticExplorerWithMetallicEd76f6f967224c458c699918c688c7790_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="An illustration of a robotic explorer, with metallic textures and intricate details."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AnIllustrationOfARoboticExplorerWithMetallicEd76f6f967224c458c699918c688c7790_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnIllustrationOfARoboticExplorerWithMetallicEd76f6f967224c458c699918c688c7790_2_Image.colorStats = {
    averageColor: Color.fromHex('#9f9788'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#110000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000011')],
    minmaxRed: [Color.fromHex('#aa6622'), Color.fromHex('#ffffff')],
    minmaxGreen: [Color.fromHex('#888855'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#555566'), Color.fromHex('#ffffdd')],
    mostFrequentColor: Color.fromHex('#bbbbaa'),
    mostSaturatedColor: Color.fromHex('#332200'),
    mostGroupedColor: Color.fromHex('#eeeedd'),
    bottom: {
        averageColor: Color.fromHex('#7c766d'),
        lightestColor: Color.fromHex('#eeeeee'),
        darkestColor: Color.fromHex('#001100'),
        minmaxWhite: [Color.fromHex('#eeeeee'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#774411'), Color.fromHex('#eeeeee')],
        minmaxGreen: [Color.fromHex('#777755'), Color.fromHex('#eeeeee')],
        minmaxBlue: [Color.fromHex('#555566'), Color.fromHex('#eeeedd')],
        mostFrequentColor: Color.fromHex('#bbbbaa'),
        mostSaturatedColor: Color.fromHex('#111100'),
        mostGroupedColor: Color.fromHex('#ccccbb'),
    },
} satisfies IImageColorStats;
