/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_neural_networ_ac3aa57d-ed4f-49ad-ae2b-f979aad43b7e-0_2.json';
import source from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_neural_networ_ac3aa57d-ed4f-49ad-ae2b-f979aad43b7e-0_2.png';

/**
 * Image of A wallpaper with a simple graphic of a neural network, against a background of complementary colors.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithASimpleGraphicOfANeuralNetworAc3aa57dEd4f49adAe2bF979aad43b7e0_2_Image() {
    return (
        <Image
            alt="A wallpaper with a simple graphic of a neural network, against a background of complementary colors."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperWithASimpleGraphicOfANeuralNetworAc3aa57dEd4f49adAe2bF979aad43b7e0_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperWithASimpleGraphicOfANeuralNetworAc3aa57dEd4f49adAe2bF979aad43b7e0_2_Image.colorStats = {
    averageColor: Color.fromHex('#2a161f'),
    lightestColor: Color.fromHex('#117fb5'),
    darkestColor: Color.fromHex('#090001'),
    minmaxWhite: [Color.fromHex('#e8c243'), Color.fromHex('#00000a')],
    minmaxRed: [Color.fromHex('#e62d16'), Color.fromHex('#117fb5')],
    minmaxGreen: [Color.fromHex('#7e8c52'), Color.fromHex('#f3322f')],
    minmaxBlue: [Color.fromHex('#0e6b9c'), Color.fromHex('#ecc230')],
    mostFrequentColor: Color.fromHex('#28555a'),
    mostSaturatedColor: Color.fromHex('#31000b'),
    mostGroupedColor: Color.fromHex('#190b1b'),
    bottom: {
        averageColor: Color.fromHex('#161c27'),
        lightestColor: Color.fromHex('#117fb5'),
        darkestColor: Color.fromHex('#140400'),
        minmaxWhite: [Color.fromHex('#e8c243'), Color.fromHex('#070210')],
        minmaxRed: [Color.fromHex('#d32a24'), Color.fromHex('#117fb5')],
        minmaxGreen: [Color.fromHex('#7e8c52'), Color.fromHex('#ef3923')],
        minmaxBlue: [Color.fromHex('#0e6b9c'), Color.fromHex('#ecc230')],
        mostFrequentColor: Color.fromHex('#28555a'),
        mostSaturatedColor: Color.fromHex('#2e0009'),
        mostGroupedColor: Color.fromHex('#190b1b'),
    },
} satisfies IImageColorStats;
