/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_futuristic_laboratory_where_ainauts_use_ai_and_adv_d3b703f1-a0f5-40af-8cb2-2ad681c6f23f-0_2.json';
import source from './Pavol_Hejn_a_futuristic_laboratory_where_ainauts_use_ai_and_adv_d3b703f1-a0f5-40af-8cb2-2ad681c6f23f-0_2.png';

/**
 * Image of A futuristic laboratory where AInauts use AI and advanced technology to create new forms of life.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AFuturisticLaboratoryWhereAinautsUseAiAndAdvD3b703f1A0f540af8cb22ad681c6f23f0_2_Image() {
    return (
        <Image
            alt="A futuristic laboratory where AInauts use AI and advanced technology to create new forms of life."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AFuturisticLaboratoryWhereAinautsUseAiAndAdvD3b703f1A0f540af8cb22ad681c6f23f0_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AFuturisticLaboratoryWhereAinautsUseAiAndAdvD3b703f1A0f540af8cb22ad681c6f23f0_2_Image.colorStats = {
    averageColor: Color.fromHex('#293843'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000001'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000001')],
    minmaxRed: [Color.fromHex('#684c33'), Color.fromHex('#daffff')],
    minmaxGreen: [Color.fromHex('#557c82'), Color.fromHex('#fffeff')],
    minmaxBlue: [Color.fromHex('#295f82'), Color.fromHex('#fffffd')],
    mostFrequentColor: Color.fromHex('#000102'),
    mostSaturatedColor: Color.fromHex('#000205'),
    mostGroupedColor: Color.fromHex('#0b0e12'),
    bottom: {
        averageColor: Color.fromHex('#19262f'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000001'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000001')],
        minmaxRed: [Color.fromHex('#684c33'), Color.fromHex('#e7ffff')],
        minmaxGreen: [Color.fromHex('#4b7780'), Color.fromHex('#fffeff')],
        minmaxBlue: [Color.fromHex('#2b5477'), Color.fromHex('#ffffff')],
        mostFrequentColor: Color.fromHex('#000102'),
        mostSaturatedColor: Color.fromHex('#000205'),
        mostGroupedColor: Color.fromHex('#0b0e12'),
    },
} satisfies IImageColorStats;
