/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_close_up_of_a_ladybug_on_a_leaf_c86301bd-e6d0-406d-b790-12cd62d11ebb-0_1.json';
import source from './Pavol_Hejn_a_close_up_of_a_ladybug_on_a_leaf_c86301bd-e6d0-406d-b790-12cd62d11ebb-0_1.png';

/**
 * Image of A close-up of a ladybug on a leaf
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ACloseUpOfALadybugOnALeafC86301bdE6d0406dB79012cd62d11ebb0_1_Image(props: IWallpaperComponentProps) {
    const { width, quality } = props;

    return (
        <Image
            alt="A close-up of a ladybug on a leaf"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ACloseUpOfALadybugOnALeafC86301bdE6d0406dB79012cd62d11ebb0_1_Image.metadata = metadata satisfies IWallpaperMetadata;
ACloseUpOfALadybugOnALeafC86301bdE6d0406dB79012cd62d11ebb0_1_Image.colorStats = {
    averageColor: Color.fromHex('#334313'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#004400'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#cc1100'), Color.fromHex('#ddffff')],
    minmaxGreen: [Color.fromHex('#77cc00'), Color.fromHex('#bb0000')],
    minmaxBlue: [Color.fromHex('#445577'), Color.fromHex('#ffffaa')],
    mostFrequentColor: Color.fromHex('#001100'),
    mostSaturatedColor: Color.fromHex('#225500'),
    mostGroupedColor: Color.fromHex('#111100'),
    bottom: {
        averageColor: Color.fromHex('#366217'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#004400'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#883333'), Color.fromHex('#ddffff')],
        minmaxGreen: [Color.fromHex('#77cc00'), Color.fromHex('#ffffff')],
        minmaxBlue: [Color.fromHex('#445577'), Color.fromHex('#ffffaa')],
        mostFrequentColor: Color.fromHex('#001100'),
        mostSaturatedColor: Color.fromHex('#225500'),
        mostGroupedColor: Color.fromHex('#337711'),
    },
} satisfies IImageColorStats;
