/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_photograph_of_a_meteor_shower_with_bright_streaks_524be76c_e273_4cd5_80e2_20b9e59d174f_0_1 from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__524be76c-e273-4cd5-80e2-20b9e59d174f-0_1.png';
import metadata from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__524be76c-e273-4cd5-80e2-20b9e59d174f-0_1.json';
import { IWallpaperMetadata } from '../IWallpaperComponent';

/**
 * Image of a photograph of a meteor shower with bright streaks  524be76c-e273-4cd5-80e2-20b9e59d174f-0
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function APhotographOfAMeteorShowerWithBrightStreaks524be76cE2734cd580e220b9e59d174f0_1_Image() {
    return (
        <Image
            alt="a photograph of a meteor shower with bright streaks  524be76c-e273-4cd5-80e2-20b9e59d174f-0"
            src={a_photograph_of_a_meteor_shower_with_bright_streaks_524be76c_e273_4cd5_80e2_20b9e59d174f_0_1}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

APhotographOfAMeteorShowerWithBrightStreaks524be76cE2734cd580e220b9e59d174f0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
