/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import metadata from './Pavol_Hejn_a_wooden_wooden_beam_in_the_shape_of_an_arm_in_the_s_72f413fc-fa23-4e0e-a4da-289234f2ee58-0_2.json';
import a_wooden_wooden_beam_in_the_shape_of_an_arm_in_the_s_72f413fc_fa23_4e0e_a4da_289234f2ee58_0_2 from './Pavol_Hejn_a_wooden_wooden_beam_in_the_shape_of_an_arm_in_the_s_72f413fc-fa23-4e0e-a4da-289234f2ee58-0_2.png';

/**
 * Image of a wooden wooden beam in the shape of an arm in the s 72f413fc-fa23-4e0e-a4da-289234f2ee58-0
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AWoodenWoodenBeamInTheShapeOfAnArmInTheS72f413fcFa234e0eA4da289234f2ee580_2_Image() {
    return (
        <Image
            alt="a wooden wooden beam in the shape of an arm in the s 72f413fc-fa23-4e0e-a4da-289234f2ee58-0"
            src={a_wooden_wooden_beam_in_the_shape_of_an_arm_in_the_s_72f413fc_fa23_4e0e_a4da_289234f2ee58_0_2}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWoodenWoodenBeamInTheShapeOfAnArmInTheS72f413fcFa234e0eA4da289234f2ee580_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWoodenWoodenBeamInTheShapeOfAnArmInTheS72f413fcFa234e0eA4da289234f2ee580_2_Image.colorStats = {
    averageColor: Color.fromHex('#5f502e'),
    lightestColor: Color.fromHex('#fafdf3'),
    darkestColor: Color.fromHex('#050300'),
    mostFrequentColor: Color.fromHex('#13120c'),
    leastFrequentColor: Color.fromHex('#131410'),
} satisfies IImageColorStats;
