/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import metadata from './Pavol_Hejn_a_wallpaper_featuring_a_collage_of_futuristic_techno_31f096df-b652-4e89-b69b-16203b15e2a6-0_2.json';
import a_wallpaper_featuring_a_collage_of_futuristic_techno_31f096df_b652_4e89_b69b_16203b15e2a6_0_2 from './Pavol_Hejn_a_wallpaper_featuring_a_collage_of_futuristic_techno_31f096df-b652-4e89-b69b-16203b15e2a6-0_2.png';

/**
 * Image of a wallpaper featuring a collage of futuristic techno 31f096df-b652-4e89-b69b-16203b15e2a6-0
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AWallpaperFeaturingACollageOfFuturisticTechno31f096dfB6524e89B69b16203b15e2a60_2_Image() {
    return (
        <Image
            alt="a wallpaper featuring a collage of futuristic techno 31f096df-b652-4e89-b69b-16203b15e2a6-0"
            src={a_wallpaper_featuring_a_collage_of_futuristic_techno_31f096df_b652_4e89_b69b_16203b15e2a6_0_2}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperFeaturingACollageOfFuturisticTechno31f096dfB6524e89B69b16203b15e2a60_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperFeaturingACollageOfFuturisticTechno31f096dfB6524e89B69b16203b15e2a60_2_Image.colorStats = {
    averageColor: Color.fromHex('#15292b'),
    lightestColor: Color.fromHex('#d7fff2'),
    darkestColor: Color.fromHex('#000000'),
    mostFrequentColor: Color.fromHex('#061316'),
    leastFrequentColor: Color.fromHex('#052730'),
} satisfies IImageColorStats;
