/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_surreal_landscape_of_alien_planets_and_strange_oth_a12472f1-e765-48b4-aa7a-71de0ff5e169-0_2.json';
import source from './Pavol_Hejn_a_surreal_landscape_of_alien_planets_and_strange_oth_a12472f1-e765-48b4-aa7a-71de0ff5e169-0_2.png';

/**
 * Image of A surreal landscape of alien planets and strange, otherworldly creatures.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function ASurrealLandscapeOfAlienPlanetsAndStrangeOthA12472f1E76548b4Aa7a71de0ff5e1690_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A surreal landscape of alien planets and strange, otherworldly creatures."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ASurrealLandscapeOfAlienPlanetsAndStrangeOthA12472f1E76548b4Aa7a71de0ff5e1690_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ASurrealLandscapeOfAlienPlanetsAndStrangeOthA12472f1E76548b4Aa7a71de0ff5e1690_2_Image.colorStats = {
    averageColor: Color.fromHex('#726850'),
    lightestColor: Color.fromHex('#cceeee'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#eeeedd'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#994411'), Color.fromHex('#cceeee')],
    minmaxGreen: [Color.fromHex('#559966'), Color.fromHex('#ffddcc')],
    minmaxBlue: [Color.fromHex('#556688'), Color.fromHex('#ffffaa')],
    mostFrequentColor: Color.fromHex('#221111'),
    mostSaturatedColor: Color.fromHex('#001122'),
    mostGroupedColor: Color.fromHex('#112222'),
    bottom: {
        averageColor: Color.fromHex('#62523a'),
        lightestColor: Color.fromHex('#eeeedd'),
        darkestColor: Color.fromHex('#110000'),
        minmaxWhite: [Color.fromHex('#eeeedd'), Color.fromHex('#110000')],
        minmaxRed: [Color.fromHex('#994411'), Color.fromHex('#aaeedd')],
        minmaxGreen: [Color.fromHex('#559966'), Color.fromHex('#330011')],
        minmaxBlue: [Color.fromHex('#556688'), Color.fromHex('#eeeecc')],
        mostFrequentColor: Color.fromHex('#221111'),
        mostSaturatedColor: Color.fromHex('#332200'),
        mostGroupedColor: Color.fromHex('#221111'),
    },
} satisfies IImageColorStats;
