/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_minimalist_graphic_of_a_leaf_for_an_environmental__78fd9506-5218-4175-a1f1-baa131d72683-0_3.json';
import source from './Pavol_Hejn_a_minimalist_graphic_of_a_leaf_for_an_environmental__78fd9506-5218-4175-a1f1-baa131d72683-0_3.png';

/**
 * Image of A minimalist graphic of a leaf for an environmental or sustainable living website
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AMinimalistGraphicOfALeafForAnEnvironmental78fd950652184175A1f1Baa131d726830_3_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A minimalist graphic of a leaf for an environmental or sustainable living website"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AMinimalistGraphicOfALeafForAnEnvironmental78fd950652184175A1f1Baa131d726830_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AMinimalistGraphicOfALeafForAnEnvironmental78fd950652184175A1f1Baa131d726830_3_Image.colorStats = {
    averageColor: Color.fromHex('#e1e4d2'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#224422'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#333322')],
    minmaxRed: [Color.fromHex('#444433'), Color.fromHex('#eeffff')],
    minmaxGreen: [Color.fromHex('#558855'), Color.fromHex('#ffeeff')],
    minmaxBlue: [Color.fromHex('#445555'), Color.fromHex('#ffffee')],
    mostFrequentColor: Color.fromHex('#eeeedd'),
    mostSaturatedColor: Color.fromHex('#446633'),
    mostGroupedColor: Color.fromHex('#eeeedd'),
    bottom: {
        averageColor: Color.fromHex('#e6e8d6'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#224422'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#224422')],
        minmaxRed: [Color.fromHex('#555544'), Color.fromHex('#eeffff')],
        minmaxGreen: [Color.fromHex('#558855'), Color.fromHex('#ffeeff')],
        minmaxBlue: [Color.fromHex('#445555'), Color.fromHex('#ffffee')],
        mostFrequentColor: Color.fromHex('#eeeedd'),
        mostSaturatedColor: Color.fromHex('#336644'),
        mostGroupedColor: Color.fromHex('#eeeedd'),
    },
} satisfies IImageColorStats;
