/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_close_up_of_an_ant_on_a_leaf_f363d91f-6765-4c45-8e92-3a59136d650d-0_2.json';
import source from './Pavol_Hejn_a_close_up_of_an_ant_on_a_leaf_f363d91f-6765-4c45-8e92-3a59136d650d-0_2.png';

/**
 * Image of A close-up of an ant on a leaf
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function ACloseUpOfAnAntOnALeafF363d91f67654c458e923a59136d650d0_2_Image(props: IWallpaperComponentProps) {
    const { width, quality } = props;

    return (
        <Image
            alt="A close-up of an ant on a leaf"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ACloseUpOfAnAntOnALeafF363d91f67654c458e923a59136d650d0_2_Image.metadata = metadata satisfies IWallpaperMetadata;
ACloseUpOfAnAntOnALeafF363d91f67654c458e923a59136d650d0_2_Image.colorStats = {
    averageColor: Color.fromHex('#2f3c0e'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#cc2200'), Color.fromHex('#eeffff')],
    minmaxGreen: [Color.fromHex('#55aa00'), Color.fromHex('#bb0000')],
    minmaxBlue: [Color.fromHex('#556677'), Color.fromHex('#ffcc11')],
    mostFrequentColor: Color.fromHex('#224400'),
    mostSaturatedColor: Color.fromHex('#110000'),
    mostGroupedColor: Color.fromHex('#110000'),
    bottom: {
        averageColor: Color.fromHex('#48731a'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#dd4400'), Color.fromHex('#eeffff')],
        minmaxGreen: [Color.fromHex('#55aa00'), Color.fromHex('#ffeeff')],
        minmaxBlue: [Color.fromHex('#443333'), Color.fromHex('#ddff55')],
        mostFrequentColor: Color.fromHex('#224400'),
        mostSaturatedColor: Color.fromHex('#001100'),
        mostGroupedColor: Color.fromHex('#000000'),
    },
} satisfies IImageColorStats;
