/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_abstract_image_of_a_spaceship_traveling_through_a_221581f1-6815-4937-ab9f-c37d5e2536ac-0_0.json';
import source from './Pavol_Hejn_an_abstract_image_of_a_spaceship_traveling_through_a_221581f1-6815-4937-ab9f-c37d5e2536ac-0_0.png';

/**
 * Image of An abstract image of a spaceship traveling through a wormhole, with bright colors and surreal patterns.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AnAbstractImageOfASpaceshipTravelingThroughA221581f168154937Ab9fC37d5e2536ac0_0_Image() {
    return (
        <Image
            alt="An abstract image of a spaceship traveling through a wormhole, with bright colors and surreal patterns."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AnAbstractImageOfASpaceshipTravelingThroughA221581f168154937Ab9fC37d5e2536ac0_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnAbstractImageOfASpaceshipTravelingThroughA221581f168154937Ab9fC37d5e2536ac0_0_Image.colorStats = {
    averageColor: Color.fromHex('#434547'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000d00'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#c63917'), Color.fromHex('#94fff3')],
    minmaxGreen: [Color.fromHex('#41b967'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#183a8e'), Color.fromHex('#fff99e')],
    mostFrequentColor: Color.fromHex('#000610'),
    mostSaturatedColor: Color.fromHex('#000a0d'),
    mostGroupedColor: Color.fromHex('#050a14'),
    bottom: {
        averageColor: Color.fromHex('#30333c'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000a00'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#a93212'), Color.fromHex('#3bf2bf')],
        minmaxGreen: [Color.fromHex('#41b967'), Color.fromHex('#ffffff')],
        minmaxBlue: [Color.fromHex('#3d397a'), Color.fromHex('#ffffdd')],
        mostFrequentColor: Color.fromHex('#000610'),
        mostSaturatedColor: Color.fromHex('#00101a'),
        mostGroupedColor: Color.fromHex('#050a14'),
    },
} satisfies IImageColorStats;
