/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_virtual_assis_65d75275-9d15-4942-bb06-921f5fd913be-0_1.json';
import source from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_virtual_assis_65d75275-9d15-4942-bb06-921f5fd913be-0_1.png';

/**
 * Image of A wallpaper with a simple graphic of a virtual assistant or chatbot, with space for messages and alerts.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithASimpleGraphicOfAVirtualAssis65d752759d154942Bb06921f5fd913be0_1_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A wallpaper with a simple graphic of a virtual assistant or chatbot, with space for messages and alerts."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AWallpaperWithASimpleGraphicOfAVirtualAssis65d752759d154942Bb06921f5fd913be0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperWithASimpleGraphicOfAVirtualAssis65d752759d154942Bb06921f5fd913be0_1_Image.colorStats = {
    averageColor: Color.fromHex('#293f50'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#112222'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#112222')],
    minmaxRed: [Color.fromHex('#bb4433'), Color.fromHex('#66ffff')],
    minmaxGreen: [Color.fromHex('#229999'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#225577'), Color.fromHex('#ffffee')],
    mostFrequentColor: Color.fromHex('#223344'),
    mostSaturatedColor: Color.fromHex('#113355'),
    mostGroupedColor: Color.fromHex('#112233'),
    bottom: {
        averageColor: Color.fromHex('#354857'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#111122'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#111122')],
        minmaxRed: [Color.fromHex('#555566'), Color.fromHex('#77eeee')],
        minmaxGreen: [Color.fromHex('#557777'), Color.fromHex('#ffffff')],
        minmaxBlue: [Color.fromHex('#556688'), Color.fromHex('#ffffff')],
        mostFrequentColor: Color.fromHex('#223344'),
        mostSaturatedColor: Color.fromHex('#003333'),
        mostGroupedColor: Color.fromHex('#112233'),
    },
} satisfies IImageColorStats;
