/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_illustration_of_a_futuristic_astronaut_in_a_sleek_efccf71a-02b5-4d30-896a-7c0462bce256-0_1.json';
import source from './Pavol_Hejn_an_illustration_of_a_futuristic_astronaut_in_a_sleek_efccf71a-02b5-4d30-896a-7c0462bce256-0_1.png';

/**
 * Image of An illustration of a futuristic astronaut in a sleek spacesuit, standing on the surface of a distant planet.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AnIllustrationOfAFuturisticAstronautInASleekEfccf71a02b54d30896a7c0462bce2560_1_Image() {
    return (
        <Image
            alt="An illustration of a futuristic astronaut in a sleek spacesuit, standing on the surface of a distant planet."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AnIllustrationOfAFuturisticAstronautInASleekEfccf71a02b54d30896a7c0462bce2560_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnIllustrationOfAFuturisticAstronautInASleekEfccf71a02b54d30896a7c0462bce2560_1_Image.colorStats = {
    averageColor: Color.fromHex('#6d7572'),
    lightestColor: Color.fromHex('#f8fffc'),
    darkestColor: Color.fromHex('#200900'),
    minmaxWhite: [Color.fromHex('#f8fffc'), Color.fromHex('#2c0100')],
    minmaxRed: [Color.fromHex('#92370c'), Color.fromHex('#e3ffff')],
    minmaxGreen: [Color.fromHex('#40786d'), Color.fromHex('#f8fffc')],
    minmaxBlue: [Color.fromHex('#346189'), Color.fromHex('#f8fffc')],
    mostFrequentColor: Color.fromHex('#3a3b40'),
    mostSaturatedColor: Color.fromHex('#521400'),
    mostGroupedColor: Color.fromHex('#2d575d'),
    bottom: {
        averageColor: Color.fromHex('#545453'),
        lightestColor: Color.fromHex('#d5f0f1'),
        darkestColor: Color.fromHex('#200900'),
        minmaxWhite: [Color.fromHex('#f0e6dc'), Color.fromHex('#120d07')],
        minmaxRed: [Color.fromHex('#8b3718'), Color.fromHex('#d5f0f1')],
        minmaxGreen: [Color.fromHex('#588780'), Color.fromHex('#f1e4dc')],
        minmaxBlue: [Color.fromHex('#284e62'), Color.fromHex('#ffe2c4')],
        mostFrequentColor: Color.fromHex('#3a3b40'),
        mostSaturatedColor: Color.fromHex('#521400'),
        mostGroupedColor: Color.fromHex('#284152'),
    },
} satisfies IImageColorStats;
