/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_vintage_style_travel_poster_of_a_distant_planet_wi_732cc9d1-51eb-4a34-87c6-78ba348409b7-0_1.json';
import source from './Pavol_Hejn_a_vintage_style_travel_poster_of_a_distant_planet_wi_732cc9d1-51eb-4a34-87c6-78ba348409b7-0_1.png';

/**
 * Image of A vintage-style travel poster of a distant planet, with bold typography and an artistic rendering of the landscape.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AVintageStyleTravelPosterOfADistantPlanetWi732cc9d151eb4a3487c678ba348409b70_1_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A vintage-style travel poster of a distant planet, with bold typography and an artistic rendering of the landscape."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AVintageStyleTravelPosterOfADistantPlanetWi732cc9d151eb4a3487c678ba348409b70_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AVintageStyleTravelPosterOfADistantPlanetWi732cc9d151eb4a3487c678ba348409b70_1_Image.colorStats = {
    averageColor: Color.fromHex('#9a6a4a'),
    lightestColor: Color.fromHex('#ffddbb'),
    darkestColor: Color.fromHex('#331100'),
    minmaxWhite: [Color.fromHex('#ffeebb'), Color.fromHex('#111111')],
    minmaxRed: [Color.fromHex('#cc3311'), Color.fromHex('#ffeebb')],
    minmaxGreen: [Color.fromHex('#339988'), Color.fromHex('#cc3311')],
    minmaxBlue: [Color.fromHex('#115577'), Color.fromHex('#ffbb33')],
    mostFrequentColor: Color.fromHex('#111111'),
    mostSaturatedColor: Color.fromHex('#331100'),
    mostGroupedColor: Color.fromHex('#eecc88'),
    bottom: {
        averageColor: Color.fromHex('#7a4639'),
        lightestColor: Color.fromHex('#eeddaa'),
        darkestColor: Color.fromHex('#331100'),
        minmaxWhite: [Color.fromHex('#eeddaa'), Color.fromHex('#111111')],
        minmaxRed: [Color.fromHex('#cc3322'), Color.fromHex('#eeddaa')],
        minmaxGreen: [Color.fromHex('#999966'), Color.fromHex('#cc3322')],
        minmaxBlue: [Color.fromHex('#555566'), Color.fromHex('#eedd99')],
        mostFrequentColor: Color.fromHex('#111111'),
        mostSaturatedColor: Color.fromHex('#331100'),
        mostGroupedColor: Color.fromHex('#774444'),
    },
} satisfies IImageColorStats;
