/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_abstract_illustration_of_an_ai_powered_chatbot_wi_cdfd5a3a-1160-47d6-8e4f-64966cd90be8-0_3.json';
import source from './Pavol_Hejn_an_abstract_illustration_of_an_ai_powered_chatbot_wi_cdfd5a3a-1160-47d6-8e4f-64966cd90be8-0_3.png';

/**
 * Image of An abstract illustration of an AI-powered chatbot, with sleek and modern graphics and a minimalist color scheme.
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AnAbstractIllustrationOfAnAiPoweredChatbotWiCdfd5a3a116047d68e4f64966cd90be80_3_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="An abstract illustration of an AI-powered chatbot, with sleek and modern graphics and a minimalist color scheme."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AnAbstractIllustrationOfAnAiPoweredChatbotWiCdfd5a3a116047d68e4f64966cd90be80_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnAbstractIllustrationOfAnAiPoweredChatbotWiCdfd5a3a116047d68e4f64966cd90be80_3_Image.colorStats = {
    averageColor: Color.fromHex('#b77673'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#ee1111'), Color.fromHex('#22ccdd')],
    minmaxGreen: [Color.fromHex('#44bb66'), Color.fromHex('#ee0055')],
    minmaxBlue: [Color.fromHex('#002288'), Color.fromHex('#ffffdd')],
    mostFrequentColor: Color.fromHex('#ee5566'),
    mostSaturatedColor: Color.fromHex('#001122'),
    mostGroupedColor: Color.fromHex('#ffbb99'),
    bottom: {
        averageColor: Color.fromHex('#ae5764'),
        lightestColor: Color.fromHex('#eeeeff'),
        darkestColor: Color.fromHex('#330000'),
        minmaxWhite: [Color.fromHex('#ffffee'), Color.fromHex('#000011')],
        minmaxRed: [Color.fromHex('#ee0022'), Color.fromHex('#ccffff')],
        minmaxGreen: [Color.fromHex('#44aa88'), Color.fromHex('#ee0033')],
        minmaxBlue: [Color.fromHex('#005599'), Color.fromHex('#ffffdd')],
        mostFrequentColor: Color.fromHex('#ee5566'),
        mostSaturatedColor: Color.fromHex('#001122'),
        mostGroupedColor: Color.fromHex('#ee5566'),
    },
} satisfies IImageColorStats;
