/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_digital_image_of_a_black_hole_with_the_distorted_s_c6ec64aa-c043-4909-8d9a-bd9b4f7f0e4b-0_1.json';
import source from './Pavol_Hejn_a_digital_image_of_a_black_hole_with_the_distorted_s_c6ec64aa-c043-4909-8d9a-bd9b4f7f0e4b-0_1.png';

/**
 * Image of A digital image of a black hole, with the distorted shapes and bright colors representing the extreme gravity.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ADigitalImageOfABlackHoleWithTheDistortedSC6ec64aaC04349098d9aBd9b4f7f0e4b0_1_Image() {
    return (
        <Image
            alt="A digital image of a black hole, with the distorted shapes and bright colors representing the extreme gravity."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ADigitalImageOfABlackHoleWithTheDistortedSC6ec64aaC04349098d9aBd9b4f7f0e4b0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ADigitalImageOfABlackHoleWithTheDistortedSC6ec64aaC04349098d9aBd9b4f7f0e4b0_1_Image.colorStats = {
    averageColor: Color.fromHex('#251d19'),
    lightestColor: Color.fromHex('#fffffe'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#fffffe'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#ce430f'), Color.fromHex('#b1fefd')],
    minmaxGreen: [Color.fromHex('#5f9e73'), Color.fromHex('#fffffe')],
    minmaxBlue: [Color.fromHex('#2b4984'), Color.fromHex('#fbef44')],
    mostFrequentColor: Color.fromHex('#000000'),
    mostSaturatedColor: Color.fromHex('#000100'),
    mostGroupedColor: Color.fromHex('#000000'),
    bottom: {
        averageColor: Color.fromHex('#2c231a'),
        lightestColor: Color.fromHex('#e7ffff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#f1fdfa'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#ce430f'), Color.fromHex('#b1fefd')],
        minmaxGreen: [Color.fromHex('#5f9e73'), Color.fromHex('#f1fdfa')],
        minmaxBlue: [Color.fromHex('#3e4b86'), Color.fromHex('#fbef44')],
        mostFrequentColor: Color.fromHex('#000000'),
        mostSaturatedColor: Color.fromHex('#000001'),
        mostGroupedColor: Color.fromHex('#000000'),
    },
} satisfies IImageColorStats;
