/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import metadata from './Pavol_Hejn_a_group_of_ainauts_in_a_space_station_watching_as_a__056d488d-cbd3-4ae0-aa4b-11a3b5653109-0_0.json';
import a_group_of_ainauts_in_a_space_station_watching_as_a_56d488d_cbd3_4ae0_aa4b_11a3b5653109_0_0_0 from './Pavol_Hejn_a_group_of_ainauts_in_a_space_station_watching_as_a__056d488d-cbd3-4ae0-aa4b-11a3b5653109-0_0.png';

/**
 * Image of a group of ainauts in a space station watching as a 56d488d-cbd3-4ae0-aa4b-11a3b5653109-0 0
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AGroupOfAinautsInASpaceStationWatchingAsA56d488dCbd34ae0Aa4b11a3b565310900_0_Image() {
    return (
        <Image
            alt="a group of ainauts in a space station watching as a 56d488d-cbd3-4ae0-aa4b-11a3b5653109-0 0"
            src={a_group_of_ainauts_in_a_space_station_watching_as_a_56d488d_cbd3_4ae0_aa4b_11a3b5653109_0_0_0}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AGroupOfAinautsInASpaceStationWatchingAsA56d488dCbd34ae0Aa4b11a3b565310900_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AGroupOfAinautsInASpaceStationWatchingAsA56d488dCbd34ae0Aa4b11a3b565310900_0_Image.colorStats = {
    averageColor: Color.fromHex('#545855'),
    lightestColor: Color.fromHex('#fdfffa'),
    darkestColor: Color.fromHex('#000000'),
    mostFrequentColor: Color.fromHex('#262e39'),
    leastFrequentColor: Color.fromHex('#202331'),
} satisfies IImageColorStats;
