/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_close_up_of_a_bee_on_a_flower_d508a146-6242-43d8-8d89-a0db7e936f73-0_1.json';
import source from './Pavol_Hejn_a_close_up_of_a_bee_on_a_flower_d508a146-6242-43d8-8d89-a0db7e936f73-0_1.png';

/**
 * Image of A close-up of a bee on a flower
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ACloseUpOfABeeOnAFlowerD508a146624243d88d89A0db7e936f730_1_Image(props: IWallpaperComponentProps) {
    const { width, quality } = props;

    return (
        <Image
            alt="A close-up of a bee on a flower"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ACloseUpOfABeeOnAFlowerD508a146624243d88d89A0db7e936f730_1_Image.metadata = metadata satisfies IWallpaperMetadata;
ACloseUpOfABeeOnAFlowerD508a146624243d88d89A0db7e936f730_1_Image.colorStats = {
    averageColor: Color.fromHex('#6f394b'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#aa2211'), Color.fromHex('#ffffff')],
    minmaxGreen: [Color.fromHex('#777755'), Color.fromHex('#ff99dd')],
    minmaxBlue: [Color.fromHex('#004499'), Color.fromHex('#ffff99')],
    mostFrequentColor: Color.fromHex('#330000'),
    mostSaturatedColor: Color.fromHex('#110011'),
    mostGroupedColor: Color.fromHex('#000011'),
    bottom: {
        averageColor: Color.fromHex('#7b3043'),
        lightestColor: Color.fromHex('#ffbbee'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffdddd'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#aa2211'), Color.fromHex('#eedddd')],
        minmaxGreen: [Color.fromHex('#887755'), Color.fromHex('#ffbbee')],
        minmaxBlue: [Color.fromHex('#773366'), Color.fromHex('#ffddbb')],
        mostFrequentColor: Color.fromHex('#330000'),
        mostSaturatedColor: Color.fromHex('#110011'),
        mostGroupedColor: Color.fromHex('#440011'),
    },
} satisfies IImageColorStats;
