/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_team_of_ainauts_piloting_a_small_spacecraft_throug_bdbfc142-36bb-455b-aeac-e31744cd233b-0_3.json';
import source from './Pavol_Hejn_a_team_of_ainauts_piloting_a_small_spacecraft_throug_bdbfc142-36bb-455b-aeac-e31744cd233b-0_3.png';

/**
 * Image of A team of AInauts piloting a small spacecraft through a dangerous asteroid field, with debris flying all around them.
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function ATeamOfAinautsPilotingASmallSpacecraftThrougBdbfc14236bb455bAeacE31744cd233b0_3_Image() {
    return (
        <Image
            alt="A team of AInauts piloting a small spacecraft through a dangerous asteroid field, with debris flying all around them."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ATeamOfAinautsPilotingASmallSpacecraftThrougBdbfc14236bb455bAeacE31744cd233b0_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ATeamOfAinautsPilotingASmallSpacecraftThrougBdbfc14236bb455bAeacE31744cd233b0_3_Image.colorStats = {
    averageColor: Color.fromHex('#31343d'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#943d33'), Color.fromHex('#f3ffff')],
    minmaxGreen: [Color.fromHex('#557772'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#3f4a67'), Color.fromHex('#ffffda')],
    mostFrequentColor: Color.fromHex('#05070b'),
    mostSaturatedColor: Color.fromHex('#000004'),
    mostGroupedColor: Color.fromHex('#0e0f13'),
    bottom: {
        averageColor: Color.fromHex('#202127'),
        lightestColor: Color.fromHex('#f5ffff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#fbfffc'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#8a4c2e'), Color.fromHex('#f5ffff')],
        minmaxGreen: [Color.fromHex('#557772'), Color.fromHex('#fbfffc')],
        minmaxBlue: [Color.fromHex('#374861'), Color.fromHex('#fbfffc')],
        mostFrequentColor: Color.fromHex('#05070b'),
        mostSaturatedColor: Color.fromHex('#000006'),
        mostGroupedColor: Color.fromHex('#0e0f13'),
    },
} satisfies IImageColorStats;
