/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_digital_image_of_a_galaxy_collision_with_swirling__f91b24a5-b84c-4bab-bacc-bd82e09756b0-0_1.json';
import source from './Pavol_Hejn_a_digital_image_of_a_galaxy_collision_with_swirling__f91b24a5-b84c-4bab-bacc-bd82e09756b0-0_1.png';

/**
 * Image of A digital image of a galaxy collision, with swirling colors and distorted shapes representing the chaos of the event.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ADigitalImageOfAGalaxyCollisionWithSwirlingF91b24a5B84c4babBaccBd82e09756b00_1_Image() {
    return (
        <Image
            alt="A digital image of a galaxy collision, with swirling colors and distorted shapes representing the chaos of the event."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ADigitalImageOfAGalaxyCollisionWithSwirlingF91b24a5B84c4babBaccBd82e09756b00_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ADigitalImageOfAGalaxyCollisionWithSwirlingF91b24a5B84c4babBaccBd82e09756b00_1_Image.colorStats = {
    averageColor: Color.fromHex('#51323a'),
    lightestColor: Color.fromHex('#ffeeee'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffeeee'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#aa3322'), Color.fromHex('#eeeeee')],
    minmaxGreen: [Color.fromHex('#559988'), Color.fromHex('#ffeeee')],
    minmaxBlue: [Color.fromHex('#225588'), Color.fromHex('#ffeedd')],
    mostFrequentColor: Color.fromHex('#552233'),
    mostSaturatedColor: Color.fromHex('#110011'),
    mostGroupedColor: Color.fromHex('#111111'),
    bottom: {
        averageColor: Color.fromHex('#39262d'),
        lightestColor: Color.fromHex('#eecc77'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#eecc77'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#aa3322'), Color.fromHex('#225588')],
        minmaxGreen: [Color.fromHex('#558888'), Color.fromHex('#220011')],
        minmaxBlue: [Color.fromHex('#334488'), Color.fromHex('#ffbb66')],
        mostFrequentColor: Color.fromHex('#552233'),
        mostSaturatedColor: Color.fromHex('#001111'),
        mostGroupedColor: Color.fromHex('#111111'),
    },
} satisfies IImageColorStats;
