/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_sunrise_on_a_distant_planet_d5bb2707-a5e0-4e4f-96b1-55d4003057d7-0_0.json';
import source from './Pavol_Hejn_sunrise_on_a_distant_planet_d5bb2707-a5e0-4e4f-96b1-55d4003057d7-0_0.png';

/**
 * Image of Sunrise on a distant planet
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function SunriseOnADistantPlanetD5bb2707A5e04e4f96b155d4003057d70_0_Image(props: IWallpaperComponentProps) {
    const { width, quality } = props;

    return (
        <Image
            alt="Sunrise on a distant planet"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

SunriseOnADistantPlanetD5bb2707A5e04e4f96b155d4003057d70_0_Image.metadata = metadata satisfies IWallpaperMetadata;
SunriseOnADistantPlanetD5bb2707A5e04e4f96b155d4003057d70_0_Image.colorStats = {
    averageColor: Color.fromHex('#614a50'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#220000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000011')],
    minmaxRed: [Color.fromHex('#cc3344'), Color.fromHex('#ffffff')],
    minmaxGreen: [Color.fromHex('#446666'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#113366'), Color.fromHex('#ffffaa')],
    mostFrequentColor: Color.fromHex('#000011'),
    mostSaturatedColor: Color.fromHex('#002233'),
    mostGroupedColor: Color.fromHex('#334455'),
    bottom: {
        averageColor: Color.fromHex('#222031'),
        lightestColor: Color.fromHex('#ffbbaa'),
        darkestColor: Color.fromHex('#000011'),
        minmaxWhite: [Color.fromHex('#ffbbaa'), Color.fromHex('#000011')],
        minmaxRed: [Color.fromHex('#bb3344'), Color.fromHex('#ffbbaa')],
        minmaxGreen: [Color.fromHex('#446666'), Color.fromHex('#ff5544')],
        minmaxBlue: [Color.fromHex('#335577'), Color.fromHex('#ffbbaa')],
        mostFrequentColor: Color.fromHex('#000011'),
        mostSaturatedColor: Color.fromHex('#001122'),
        mostGroupedColor: Color.fromHex('#223344'),
    },
} satisfies IImageColorStats;
