/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_featuring_a_stylized_illustration_of_a_d_6f5c971b-6b00-4986-b9c7-21175b40e847-0_0.json';
import source from './Pavol_Hejn_a_wallpaper_featuring_a_stylized_illustration_of_a_d_6f5c971b-6b00-4986-b9c7-21175b40e847-0_0.png';

/**
 * Image of A wallpaper featuring a stylized illustration of a dystopian future, with metallic textures and digital glitch effects.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function AWallpaperFeaturingAStylizedIllustrationOfAD6f5c971b6b004986B9c721175b40e8470_0_Image() {
    return (
        <Image
            alt="A wallpaper featuring a stylized illustration of a dystopian future, with metallic textures and digital glitch effects."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AWallpaperFeaturingAStylizedIllustrationOfAD6f5c971b6b004986B9c721175b40e8470_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperFeaturingAStylizedIllustrationOfAD6f5c971b6b004986B9c721175b40e8470_0_Image.colorStats = {
    averageColor: Color.fromHex('#394242'),
    lightestColor: Color.fromHex('#ddeeee'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#eeeedd'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#aa4422'), Color.fromHex('#ddeeee')],
    minmaxGreen: [Color.fromHex('#339988'), Color.fromHex('#eedddd')],
    minmaxBlue: [Color.fromHex('#226677'), Color.fromHex('#eeeecc')],
    mostFrequentColor: Color.fromHex('#000011'),
    mostSaturatedColor: Color.fromHex('#000011'),
    mostGroupedColor: Color.fromHex('#111111'),
    bottom: {
        averageColor: Color.fromHex('#0f1920'),
        lightestColor: Color.fromHex('#cceedd'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#cceedd'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#774433'), Color.fromHex('#cceedd')],
        minmaxGreen: [Color.fromHex('#229988'), Color.fromHex('#000011')],
        minmaxBlue: [Color.fromHex('#116677'), Color.fromHex('#cceedd')],
        mostFrequentColor: Color.fromHex('#000011'),
        mostSaturatedColor: Color.fromHex('#000011'),
        mostGroupedColor: Color.fromHex('#000011'),
    },
} satisfies IImageColorStats;
