/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
<<<<<<< HEAD
import metadata from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__524be76c-e273-4cd5-80e2-20b9e59d174f-0_1.json';
import a_photograph_of_a_meteor_shower_with_bright_streaks_524be76c_e273_4cd5_80e2_20b9e59d174f_0_1 from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__524be76c-e273-4cd5-80e2-20b9e59d174f-0_1.png';
=======
import { IImageColorStats } from '../../../../src/utils/image/computeImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__524be76c-e273-4cd5-80e2-20b9e59d174f-0_1.json';
import source from './Pavol_Hejn_a_photograph_of_a_meteor_shower_with_bright_streaks__524be76c-e273-4cd5-80e2-20b9e59d174f-0_1.png';
>>>>>>> 64e54cefb08238cf116a29d1b1a13a8a44f215de

/**
 * Image of A photograph of a meteor shower, with bright streaks of light crossing the night sky.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function APhotographOfAMeteorShowerWithBrightStreaks524be76cE2734cd580e220b9e59d174f0_1_Image() {
    return (
        <Image
            alt="A photograph of a meteor shower, with bright streaks of light crossing the night sky."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

APhotographOfAMeteorShowerWithBrightStreaks524be76cE2734cd580e220b9e59d174f0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
APhotographOfAMeteorShowerWithBrightStreaks524be76cE2734cd580e220b9e59d174f0_1_Image.colorStats = {
    averageColor: Color.fromHex('#3f2f2d'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    mostFrequentColor: Color.fromHex('#000005'),
    leastFrequentColor: Color.fromHex('#404047'),
} satisfies IImageColorStats;
