/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_photograph_of_a_full_moon_rising_over_a_mountain_r8bb8e7e_c008_4dae_a024_43af98452d3a_0_3_3 from './Pavol_Hejn_a_photograph_of_a_full_moon_rising_over_a_mountain_r_38bb8e7e-c008-4dae-a024-43af98452d3a-0_3.png';
import metadata from './Pavol_Hejn_a_photograph_of_a_full_moon_rising_over_a_mountain_r_38bb8e7e-c008-4dae-a024-43af98452d3a-0_3.json';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import { IImageColorStats } from '../../../../src/utils/image/computeImageColorStats';
import { Color } from '../../../../src/utils/color/Color';

/**
 * Image of a photograph of a full moon rising over a mountain r8bb8e7e-c008-4dae-a024-43af98452d3a-0 3
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function APhotographOfAFullMoonRisingOverAMountainR8bb8e7eC0084daeA02443af98452d3a03_3_Image() {
    return (
        <Image
            alt="a photograph of a full moon rising over a mountain r8bb8e7e-c008-4dae-a024-43af98452d3a-0 3"
            src={a_photograph_of_a_full_moon_rising_over_a_mountain_r8bb8e7e_c008_4dae_a024_43af98452d3a_0_3_3}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

APhotographOfAFullMoonRisingOverAMountainR8bb8e7eC0084daeA02443af98452d3a03_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
APhotographOfAFullMoonRisingOverAMountainR8bb8e7eC0084daeA02443af98452d3a03_3_Image.colorStats = {
    averageColor: Color.fromHex('#444c50'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    mostFrequentColor: Color.fromHex('#000000'),
    leastFrequentColor: Color.fromHex('#2b454f'),
} satisfies IImageColorStats;
