/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_repeating_pattern_of_abstract_geo_33e29040-2e35-48ec-b472-397f6d0249fb-0_2.json';
import source from './Pavol_Hejn_a_wallpaper_with_a_repeating_pattern_of_abstract_geo_33e29040-2e35-48ec-b472-397f6d0249fb-0_2.png';

/**
 * Image of A wallpaper with a repeating pattern of abstract geometric shapes and patterns, inspired by web design trends and color schemes.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithARepeatingPatternOfAbstractGeo33e290402e3548ecB472397f6d0249fb0_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A wallpaper with a repeating pattern of abstract geometric shapes and patterns, inspired by web design trends and color schemes."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AWallpaperWithARepeatingPatternOfAbstractGeo33e290402e3548ecB472397f6d0249fb0_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperWithARepeatingPatternOfAbstractGeo33e290402e3548ecB472397f6d0249fb0_2_Image.colorStats = {
    averageColor: Color.fromHex('#676654'),
    lightestColor: Color.fromHex('#eeddbb'),
    darkestColor: Color.fromHex('#001111'),
    minmaxWhite: [Color.fromHex('#eeeebb'), Color.fromHex('#001111')],
    minmaxRed: [Color.fromHex('#dd2222'), Color.fromHex('#eeeebb')],
    minmaxGreen: [Color.fromHex('#44aa77'), Color.fromHex('#dd2222')],
    minmaxBlue: [Color.fromHex('#115577'), Color.fromHex('#ffdd88')],
    mostFrequentColor: Color.fromHex('#223344'),
    mostSaturatedColor: Color.fromHex('#002222'),
    mostGroupedColor: Color.fromHex('#112233'),
    bottom: {
        averageColor: Color.fromHex('#686955'),
        lightestColor: Color.fromHex('#eeccaa'),
        darkestColor: Color.fromHex('#001111'),
        minmaxWhite: [Color.fromHex('#eeddaa'), Color.fromHex('#001111')],
        minmaxRed: [Color.fromHex('#dd3333'), Color.fromHex('#ddddaa')],
        minmaxGreen: [Color.fromHex('#338866'), Color.fromHex('#dd3333')],
        minmaxBlue: [Color.fromHex('#225577'), Color.fromHex('#ffdd88')],
        mostFrequentColor: Color.fromHex('#223344'),
        mostSaturatedColor: Color.fromHex('#002222'),
        mostGroupedColor: Color.fromHex('#112233'),
    },
} satisfies IImageColorStats;
