/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_surreal_interpretation_of_a_desert_landscape_7d9d4cf0-138e-44fd-bcd4-7c91ee111a52-0_2.json';
import source from './Pavol_Hejn_a_surreal_interpretation_of_a_desert_landscape_7d9d4cf0-138e-44fd-bcd4-7c91ee111a52-0_2.png';

/**
 * Image of A surreal interpretation of a desert landscape
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function ASurrealInterpretationOfADesertLandscape7d9d4cf0138e44fdBcd47c91ee111a520_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A surreal interpretation of a desert landscape"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ASurrealInterpretationOfADesertLandscape7d9d4cf0138e44fdBcd47c91ee111a520_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ASurrealInterpretationOfADesertLandscape7d9d4cf0138e44fdBcd47c91ee111a520_2_Image.colorStats = {
    averageColor: Color.fromHex('#a07057'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#bb3311'), Color.fromHex('#ffffff')],
    minmaxGreen: [Color.fromHex('#777755'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#555566'), Color.fromHex('#ffffaa')],
    mostFrequentColor: Color.fromHex('#331111'),
    mostSaturatedColor: Color.fromHex('#551100'),
    mostGroupedColor: Color.fromHex('#888888'),
    bottom: {
        averageColor: Color.fromHex('#9a4f33'),
        lightestColor: Color.fromHex('#ffccbb'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffddbb'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#bb3311'), Color.fromHex('#eeddbb')],
        minmaxGreen: [Color.fromHex('#776644'), Color.fromHex('#550000')],
        minmaxBlue: [Color.fromHex('#553344'), Color.fromHex('#ffcc66')],
        mostFrequentColor: Color.fromHex('#331111'),
        mostSaturatedColor: Color.fromHex('#441100'),
        mostGroupedColor: Color.fromHex('#ffaa66'),
    },
} satisfies IImageColorStats;
