/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_bridge_standing_over_a_field_in_the_style_of_dark__dab1f838-c921-4f87-99a7-efe9ed40307b-0_1.json';
import source from './Pavol_Hejn_a_bridge_standing_over_a_field_in_the_style_of_dark__dab1f838-c921-4f87-99a7-efe9ed40307b-0_1.png';

/**
 * Image of a bridge standing over a field, in the style of dark green and light azure, swiss style, 32k uhd, earthworks, heidelberg school, hikecore, forestpunk
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ABridgeStandingOverAFieldInTheStyleOfDarkDab1f838C9214f8799a7Efe9ed40307b0_1_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="a bridge standing over a field, in the style of dark green and light azure, swiss style, 32k uhd, earthworks, heidelberg school, hikecore, forestpunk"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ABridgeStandingOverAFieldInTheStyleOfDarkDab1f838C9214f8799a7Efe9ed40307b0_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ABridgeStandingOverAFieldInTheStyleOfDarkDab1f838C9214f8799a7Efe9ed40307b0_1_Image.colorStats = {
    averageColor: Color.fromHex('#5a756f'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#001100'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#775533'), Color.fromHex('#ddffff')],
    minmaxGreen: [Color.fromHex('#779944'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#005588'), Color.fromHex('#ffffff')],
    mostFrequentColor: Color.fromHex('#223322'),
    mostSaturatedColor: Color.fromHex('#001122'),
    mostGroupedColor: Color.fromHex('#bbddee'),
    bottom: {
        averageColor: Color.fromHex('#4d5c39'),
        lightestColor: Color.fromHex('#cceecc'),
        darkestColor: Color.fromHex('#001100'),
        minmaxWhite: [Color.fromHex('#cceecc'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#664433'), Color.fromHex('#cceecc')],
        minmaxGreen: [Color.fromHex('#779944'), Color.fromHex('#000011')],
        minmaxBlue: [Color.fromHex('#223344'), Color.fromHex('#cceecc')],
        mostFrequentColor: Color.fromHex('#223322'),
        mostSaturatedColor: Color.fromHex('#001111'),
        mostGroupedColor: Color.fromHex('#111111'),
    },
} satisfies IImageColorStats;
