/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_digital_painting_of_a_lone_astronaut_standing_on_t_52813773-864c-445f-a336-f22707e90136-0_0.json';
import source from './Pavol_Hejn_a_digital_painting_of_a_lone_astronaut_standing_on_t_52813773-864c-445f-a336-f22707e90136-0_0.png';

/**
 * Image of A digital painting of a lone astronaut standing on the edge of a crater, gazing out at the endless expanse of space.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function ADigitalPaintingOfALoneAstronautStandingOnT52813773864c445fA336F22707e901360_0_Image() {
    return (
        <Image
            alt="A digital painting of a lone astronaut standing on the edge of a crater, gazing out at the endless expanse of space."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

ADigitalPaintingOfALoneAstronautStandingOnT52813773864c445fA336F22707e901360_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ADigitalPaintingOfALoneAstronautStandingOnT52813773864c445fA336F22707e901360_0_Image.colorStats = {
    averageColor: Color.fromHex('#494240'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#d14d16'), Color.fromHex('#ebffff')],
    minmaxGreen: [Color.fromHex('#7d8469'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#344e87'), Color.fromHex('#fffec2')],
    mostFrequentColor: Color.fromHex('#000003'),
    mostSaturatedColor: Color.fromHex('#040002'),
    mostGroupedColor: Color.fromHex('#040409'),
    bottom: {
        averageColor: Color.fromHex('#34231c'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#b04208'), Color.fromHex('#ffffff')],
        minmaxGreen: [Color.fromHex('#888055'), Color.fromHex('#ffffff')],
        minmaxBlue: [Color.fromHex('#454451'), Color.fromHex('#ffffda')],
        mostFrequentColor: Color.fromHex('#000003'),
        mostSaturatedColor: Color.fromHex('#040002'),
        mostGroupedColor: Color.fromHex('#040409'),
    },
} satisfies IImageColorStats;
