/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_illustration_of_a_futuristic_space_elevator_with__148a2aa3-fc1a-4eaa-9083-a6250d5fab36-0_1.json';
import source from './Pavol_Hejn_an_illustration_of_a_futuristic_space_elevator_with__148a2aa3-fc1a-4eaa-9083-a6250d5fab36-0_1.png';

/**
 * Image of An illustration of a futuristic space elevator, with a cable stretching from Earth into orbit.
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function AnIllustrationOfAFuturisticSpaceElevatorWith48a2aa3Fc1a4eaa9083A6250d5fab3601_1_Image() {
    return (
        <Image
            alt="An illustration of a futuristic space elevator, with a cable stretching from Earth into orbit."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AnIllustrationOfAFuturisticSpaceElevatorWith48a2aa3Fc1a4eaa9083A6250d5fab3601_1_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnIllustrationOfAFuturisticSpaceElevatorWith48a2aa3Fc1a4eaa9083A6250d5fab3601_1_Image.colorStats = {
    averageColor: Color.fromHex('#596b7b'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#9b3a0f'), Color.fromHex('#f4ffff')],
    minmaxGreen: [Color.fromHex('#497b7a'), Color.fromHex('#fffcff')],
    minmaxBlue: [Color.fromHex('#04609e'), Color.fromHex('#ffffdc')],
    mostFrequentColor: Color.fromHex('#021a31'),
    mostSaturatedColor: Color.fromHex('#00000b'),
    mostGroupedColor: Color.fromHex('#010812'),
    bottom: {
        averageColor: Color.fromHex('#3a4959'),
        lightestColor: Color.fromHex('#fffeff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#9b3a0f'), Color.fromHex('#ffffff')],
        minmaxGreen: [Color.fromHex('#83866a'), Color.fromHex('#fffdff')],
        minmaxBlue: [Color.fromHex('#365d8c'), Color.fromHex('#ffffdc')],
        mostFrequentColor: Color.fromHex('#021a31'),
        mostSaturatedColor: Color.fromHex('#000e1f'),
        mostGroupedColor: Color.fromHex('#142840'),
    },
} satisfies IImageColorStats;
