/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_retro_futuristic_wallpaper_featuring_a_vintage_ill_944b209c-17af-4e1f-8b23-ae5e41e444e1-0_0.json';
import source from './Pavol_Hejn_a_retro_futuristic_wallpaper_featuring_a_vintage_ill_944b209c-17af-4e1f-8b23-ae5e41e444e1-0_0.png';

/**
 * Image of A retro-futuristic wallpaper featuring a vintage illustration of a robot, set against a neon-colored background.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function ARetroFuturisticWallpaperFeaturingAVintageIll944b209c17af4e1f8b23Ae5e41e444e10_0_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A retro-futuristic wallpaper featuring a vintage illustration of a robot, set against a neon-colored background."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ARetroFuturisticWallpaperFeaturingAVintageIll944b209c17af4e1f8b23Ae5e41e444e10_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ARetroFuturisticWallpaperFeaturingAVintageIll944b209c17af4e1f8b23Ae5e41e444e10_0_Image.colorStats = {
    averageColor: Color.fromHex('#473859'),
    lightestColor: Color.fromHex('#dddddd'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffddcc'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#dd2233'), Color.fromHex('#33bbcc')],
    minmaxGreen: [Color.fromHex('#22aa66'), Color.fromHex('#ff2277')],
    minmaxBlue: [Color.fromHex('#222299'), Color.fromHex('#ffee44')],
    mostFrequentColor: Color.fromHex('#223355'),
    mostSaturatedColor: Color.fromHex('#220044'),
    mostGroupedColor: Color.fromHex('#114466'),
    bottom: {
        averageColor: Color.fromHex('#2e3b5d'),
        lightestColor: Color.fromHex('#ffddcc'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffddcc'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#dd1155'), Color.fromHex('#ffff99')],
        minmaxGreen: [Color.fromHex('#22aa66'), Color.fromHex('#ff2277')],
        minmaxBlue: [Color.fromHex('#221188'), Color.fromHex('#ffee44')],
        mostFrequentColor: Color.fromHex('#223355'),
        mostSaturatedColor: Color.fromHex('#220044'),
        mostGroupedColor: Color.fromHex('#114466'),
    },
} satisfies IImageColorStats;
