/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_neural_networ_1d385dcc-8ab9-456d-a9a8-d5f4b3e6ac28-0_2.json';
import source from './Pavol_Hejn_a_wallpaper_with_a_simple_graphic_of_a_neural_networ_1d385dcc-8ab9-456d-a9a8-d5f4b3e6ac28-0_2.png';

/**
 * Image of A wallpaper with a simple graphic of a neural network, against a background of complementary colors.
 *
 * @see https://www.midjourney.com/app/jobs/2
 * @generated by generate-wallpapers-library
 */
export function AWallpaperWithASimpleGraphicOfANeuralNetwor1d385dcc8ab9456dA9a8D5f4b3e6ac280_2_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A wallpaper with a simple graphic of a neural network, against a background of complementary colors."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AWallpaperWithASimpleGraphicOfANeuralNetwor1d385dcc8ab9456dA9a8D5f4b3e6ac280_2_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperWithASimpleGraphicOfANeuralNetwor1d385dcc8ab9456dA9a8D5f4b3e6ac280_2_Image.colorStats = {
    averageColor: Color.fromHex('#6d5242'),
    lightestColor: Color.fromHex('#ddbb88'),
    darkestColor: Color.fromHex('#331111'),
    minmaxWhite: [Color.fromHex('#eecc77'), Color.fromHex('#111122')],
    minmaxRed: [Color.fromHex('#bb3322'), Color.fromHex('#66aa99')],
    minmaxGreen: [Color.fromHex('#559966'), Color.fromHex('#661144')],
    minmaxBlue: [Color.fromHex('#335577'), Color.fromHex('#eecc77')],
    mostFrequentColor: Color.fromHex('#882222'),
    mostSaturatedColor: Color.fromHex('#bb5511'),
    mostGroupedColor: Color.fromHex('#223344'),
    bottom: {
        averageColor: Color.fromHex('#472e35'),
        lightestColor: Color.fromHex('#cc9977'),
        darkestColor: Color.fromHex('#441111'),
        minmaxWhite: [Color.fromHex('#cc9977'), Color.fromHex('#221122')],
        minmaxRed: [Color.fromHex('#bb3322'), Color.fromHex('#112233')],
        minmaxGreen: [Color.fromHex('#666644'), Color.fromHex('#bb3322')],
        minmaxBlue: [Color.fromHex('#443355'), Color.fromHex('#ee9955')],
        mostFrequentColor: Color.fromHex('#882222'),
        mostSaturatedColor: Color.fromHex('#cc5511'),
        mostGroupedColor: Color.fromHex('#222233'),
    },
} satisfies IImageColorStats;
