/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_an_impressionist_style_painting_of_a_futuristic_city_85a1d760-f66a-4382-9228-545a1df4a55b-0_3.json';
import source from './Pavol_Hejn_an_impressionist_style_painting_of_a_futuristic_city_85a1d760-f66a-4382-9228-545a1df4a55b-0_3.png';

/**
 * Image of An impressionist-style painting of a futuristic cityscape, with blurred lines and bold colors creating a dreamy effect.
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AnImpressionistStylePaintingOfAFuturisticCity85a1d760F66a43829228545a1df4a55b0_3_Image() {
    return (
        <Image
            alt="An impressionist-style painting of a futuristic cityscape, with blurred lines and bold colors creating a dreamy effect."
            src={source}
            draggable="false"
            placeholder="blur"
            width={1920}
            height={1080}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AnImpressionistStylePaintingOfAFuturisticCity85a1d760F66a43829228545a1df4a55b0_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AnImpressionistStylePaintingOfAFuturisticCity85a1d760F66a43829228545a1df4a55b0_3_Image.colorStats = {
    averageColor: Color.fromHex('#5c4442'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#e60d00'), Color.fromHex('#e8ffff')],
    minmaxGreen: [Color.fromHex('#40957e'), Color.fromHex('#de0700')],
    minmaxBlue: [Color.fromHex('#104fa3'), Color.fromHex('#ffdb4d')],
    mostFrequentColor: Color.fromHex('#040b13'),
    mostSaturatedColor: Color.fromHex('#0a0004'),
    mostGroupedColor: Color.fromHex('#0d0f1b'),
    bottom: {
        averageColor: Color.fromHex('#603f3b'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#de1a0e'), Color.fromHex('#dafcff')],
        minmaxGreen: [Color.fromHex('#339d91'), Color.fromHex('#ff2b0c')],
        minmaxBlue: [Color.fromHex('#30468c'), Color.fromHex('#ffdb4d')],
        mostFrequentColor: Color.fromHex('#040b13'),
        mostSaturatedColor: Color.fromHex('#030004'),
        mostGroupedColor: Color.fromHex('#0a1019'),
    },
} satisfies IImageColorStats;
