/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_poster_style_image_of_a_mission_to_mars_with_bold__6e6533f5-7774-4664-a6c1-8ebb09cefb82-0_0.json';
import source from './Pavol_Hejn_a_poster_style_image_of_a_mission_to_mars_with_bold__6e6533f5-7774-4664-a6c1-8ebb09cefb82-0_0.png';

/**
 * Image of A poster-style image of a mission to Mars, with bold typography and a futuristic color scheme that represents the ambition of space exploration.
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function APosterStyleImageOfAMissionToMarsWithBold6e6533f577744664A6c18ebb09cefb820_0_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A poster-style image of a mission to Mars, with bold typography and a futuristic color scheme that represents the ambition of space exploration."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

APosterStyleImageOfAMissionToMarsWithBold6e6533f577744664A6c18ebb09cefb820_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
APosterStyleImageOfAMissionToMarsWithBold6e6533f577744664A6c18ebb09cefb820_0_Image.colorStats = {
    averageColor: Color.fromHex('#7c5d51'),
    lightestColor: Color.fromHex('#ffffee'),
    darkestColor: Color.fromHex('#000000'),
    minmaxWhite: [Color.fromHex('#ffffee'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#dd2211'), Color.fromHex('#eeffee')],
    minmaxGreen: [Color.fromHex('#559966'), Color.fromHex('#ff3311')],
    minmaxBlue: [Color.fromHex('#335588'), Color.fromHex('#ffffbb')],
    mostFrequentColor: Color.fromHex('#bb4422'),
    mostSaturatedColor: Color.fromHex('#551100'),
    mostGroupedColor: Color.fromHex('#222233'),
    bottom: {
        averageColor: Color.fromHex('#924e3d'),
        lightestColor: Color.fromHex('#ffffee'),
        darkestColor: Color.fromHex('#000000'),
        minmaxWhite: [Color.fromHex('#ffffee'), Color.fromHex('#000000')],
        minmaxRed: [Color.fromHex('#cc2211'), Color.fromHex('#eeffee')],
        minmaxGreen: [Color.fromHex('#55aa88'), Color.fromHex('#ffeeee')],
        minmaxBlue: [Color.fromHex('#224466'), Color.fromHex('#ffffee')],
        mostFrequentColor: Color.fromHex('#bb4422'),
        mostSaturatedColor: Color.fromHex('#000011'),
        mostGroupedColor: Color.fromHex('#222233'),
    },
} satisfies IImageColorStats;
