/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_wallpaper_featuring_an_abstract_illustration_of_a__8831a8fa-09c9-4f56-b9d2-a86ae709bbb0-0_3.json';
import source from './Pavol_Hejn_a_wallpaper_featuring_an_abstract_illustration_of_a__8831a8fa-09c9-4f56-b9d2-a86ae709bbb0-0_3.png';

/**
 * Image of A wallpaper featuring an abstract illustration of a futuristic data visualization, with sleek and modern graphics and a minimalist color scheme.
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AWallpaperFeaturingAnAbstractIllustrationOfA8831a8fa09c94f56B9d2A86ae709bbb00_3_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A wallpaper featuring an abstract illustration of a futuristic data visualization, with sleek and modern graphics and a minimalist color scheme."
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

AWallpaperFeaturingAnAbstractIllustrationOfA8831a8fa09c94f56B9d2A86ae709bbb00_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AWallpaperFeaturingAnAbstractIllustrationOfA8831a8fa09c94f56B9d2A86ae709bbb00_3_Image.colorStats = {
    averageColor: Color.fromHex('#72556c'),
    lightestColor: Color.fromHex('#eeffff'),
    darkestColor: Color.fromHex('#000011'),
    minmaxWhite: [Color.fromHex('#eeffff'), Color.fromHex('#000011')],
    minmaxRed: [Color.fromHex('#ee3355'), Color.fromHex('#eeffff')],
    minmaxGreen: [Color.fromHex('#448888'), Color.fromHex('#ee3366')],
    minmaxBlue: [Color.fromHex('#224499'), Color.fromHex('#eeffff')],
    mostFrequentColor: Color.fromHex('#222255'),
    mostSaturatedColor: Color.fromHex('#001133'),
    mostGroupedColor: Color.fromHex('#ffaa99'),
    bottom: {
        averageColor: Color.fromHex('#222348'),
        lightestColor: Color.fromHex('#eeffff'),
        darkestColor: Color.fromHex('#000011'),
        minmaxWhite: [Color.fromHex('#eeffff'), Color.fromHex('#000011')],
        minmaxRed: [Color.fromHex('#cc3355'), Color.fromHex('#eeffff')],
        minmaxGreen: [Color.fromHex('#338899'), Color.fromHex('#ee4477')],
        minmaxBlue: [Color.fromHex('#224499'), Color.fromHex('#eeffff')],
        mostFrequentColor: Color.fromHex('#222255'),
        mostSaturatedColor: Color.fromHex('#001133'),
        mostGroupedColor: Color.fromHex('#222255'),
    },
} satisfies IImageColorStats;
