/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_close_up_of_a_seagull_in_flight_b6ed2855-fc11-482d-bb90-22a09000e3c1-0_1.json';
import source from './Pavol_Hejn_a_close_up_of_a_seagull_in_flight_b6ed2855-fc11-482d-bb90-22a09000e3c1-0_1.png';

/**
 * Image of A close-up of a seagull in flight
 *
 * @see https://www.midjourney.com/app/jobs/1
 * @generated by generate-wallpapers-library
 */
export function ACloseUpOfASeagullInFlightB6ed2855Fc11482dBb9022a09000e3c10_1_Image(props: IWallpaperComponentProps) {
    const { width, quality } = props;

    return (
        <Image
            alt="A close-up of a seagull in flight"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ACloseUpOfASeagullInFlightB6ed2855Fc11482dBb9022a09000e3c10_1_Image.metadata = metadata satisfies IWallpaperMetadata;
ACloseUpOfASeagullInFlightB6ed2855Fc11482dBb9022a09000e3c10_1_Image.colorStats = {
    averageColor: Color.fromHex('#979d97'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#001100'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000000')],
    minmaxRed: [Color.fromHex('#dd2211'), Color.fromHex('#eeffff')],
    minmaxGreen: [Color.fromHex('#558866'), Color.fromHex('#ffeeff')],
    minmaxBlue: [Color.fromHex('#335577'), Color.fromHex('#ffdd55')],
    mostFrequentColor: Color.fromHex('#556677'),
    mostSaturatedColor: Color.fromHex('#221100'),
    mostGroupedColor: Color.fromHex('#ffeeee'),
    bottom: {
        averageColor: Color.fromHex('#8f9b97'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#111111'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#111111')],
        minmaxRed: [Color.fromHex('#aa4422'), Color.fromHex('#ffffff')],
        minmaxGreen: [Color.fromHex('#558866'), Color.fromHex('#ffeeff')],
        minmaxBlue: [Color.fromHex('#445577'), Color.fromHex('#ffffcc')],
        mostFrequentColor: Color.fromHex('#556677'),
        mostSaturatedColor: Color.fromHex('#994411'),
        mostGroupedColor: Color.fromHex('#557788'),
    },
} satisfies IImageColorStats;
