/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import metadata from './Pavol_Hejn_a_group_of_ainauts_standing_on_the_surface_of_a_red__e04ecc24-3900-4694-b550-f31df323741e-0_3.json';
import a_group_of_ainauts_standing_on_the_surface_of_a_red_e04ecc24_3900_4694_b550_f31df323741e_0_3 from './Pavol_Hejn_a_group_of_ainauts_standing_on_the_surface_of_a_red__e04ecc24-3900-4694-b550-f31df323741e-0_3.png';

/**
 * Image of a group of ainauts standing on the surface of a red  e04ecc24-3900-4694-b550-f31df323741e-0
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AGroupOfAinautsStandingOnTheSurfaceOfARedE04ecc2439004694B550F31df323741e0_3_Image() {
    return (
        <Image
            alt="a group of ainauts standing on the surface of a red  e04ecc24-3900-4694-b550-f31df323741e-0"
            src={a_group_of_ainauts_standing_on_the_surface_of_a_red_e04ecc24_3900_4694_b550_f31df323741e_0_3}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}

AGroupOfAinautsStandingOnTheSurfaceOfARedE04ecc2439004694B550F31df323741e0_3_Image.metadata =
    metadata satisfies IWallpaperMetadata;
AGroupOfAinautsStandingOnTheSurfaceOfARedE04ecc2439004694B550F31df323741e0_3_Image.colorStats = {
    averageColor: Color.fromHex('#a27152'),
    lightestColor: Color.fromHex('#fcfdfb'),
    darkestColor: Color.fromHex('#2f0500'),
    mostFrequentColor: Color.fromHex('#dcb88c'),
    leastFrequentColor: Color.fromHex('#88523b'),
} satisfies IImageColorStats;
