/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Color } from '../../../../src/utils/color/Color';
import { IImageColorStats } from '../../../../src/utils/image/utils/IImageColorStats';
import { IWallpaperMetadata, IWallpaperComponentProps } from '../IWallpaperComponent';
import metadata from './Pavol_Hejn_a_surreal_image_of_a_floating_island_with_a_waterfal_dca7be3d-9085-4f60-a9bd-168d5bcd3cc9-0_0.json';
import source from './Pavol_Hejn_a_surreal_image_of_a_floating_island_with_a_waterfal_dca7be3d-9085-4f60-a9bd-168d5bcd3cc9-0_0.png';

/**
 * Image of A surreal image of a floating island with a waterfall for a travel blog or agency
 *
 * @see https://www.midjourney.com/app/jobs/0
 * @generated by generate-wallpapers-library
 */
export function ASurrealImageOfAFloatingIslandWithAWaterfalDca7be3d90854f60A9bd168d5bcd3cc90_0_Image(
    props: IWallpaperComponentProps,
) {
    const { width, quality } = props;

    return (
        <Image
            alt="A surreal image of a floating island with a waterfall for a travel blog or agency"
            src={source}
            draggable="false"
            placeholder="blur"
            height={Math.round((width / 1920) * 1080)}
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
            {...{ width, quality }}
        />
    );
}

ASurrealImageOfAFloatingIslandWithAWaterfalDca7be3d90854f60A9bd168d5bcd3cc90_0_Image.metadata =
    metadata satisfies IWallpaperMetadata;
ASurrealImageOfAFloatingIslandWithAWaterfalDca7be3d90854f60A9bd168d5bcd3cc90_0_Image.colorStats = {
    averageColor: Color.fromHex('#7c8e85'),
    lightestColor: Color.fromHex('#ffffff'),
    darkestColor: Color.fromHex('#002200'),
    minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000011')],
    minmaxRed: [Color.fromHex('#774411'), Color.fromHex('#ccffff')],
    minmaxGreen: [Color.fromHex('#669944'), Color.fromHex('#ffffff')],
    minmaxBlue: [Color.fromHex('#225566'), Color.fromHex('#ffff99')],
    mostFrequentColor: Color.fromHex('#224444'),
    mostSaturatedColor: Color.fromHex('#002211'),
    mostGroupedColor: Color.fromHex('#224455'),
    bottom: {
        averageColor: Color.fromHex('#4c6868'),
        lightestColor: Color.fromHex('#ffffff'),
        darkestColor: Color.fromHex('#001100'),
        minmaxWhite: [Color.fromHex('#ffffff'), Color.fromHex('#000011')],
        minmaxRed: [Color.fromHex('#885533'), Color.fromHex('#eeffff')],
        minmaxGreen: [Color.fromHex('#669944'), Color.fromHex('#ffffff')],
        minmaxBlue: [Color.fromHex('#335566'), Color.fromHex('#ffffee')],
        mostFrequentColor: Color.fromHex('#224444'),
        mostSaturatedColor: Color.fromHex('#002222'),
        mostGroupedColor: Color.fromHex('#224455'),
    },
} satisfies IImageColorStats;
