/**
 * 🏭 GENERATED WITH 🖼️ Generate wallpapers library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import a_wallpaper_featuring_a_stylized_illustration_of_a_f_081b7e0f_3c00_428b_8549_8ca19f7e7cdf_0_3 from './Pavol_Hejn_a_wallpaper_featuring_a_stylized_illustration_of_a_f_081b7e0f-3c00-428b-8549-8ca19f7e7cdf-0_3.png';

/**
 * Image of a wallpaper featuring a stylized illustration of a f 081b7e0f-3c00-428b-8549-8ca19f7e7cdf-0
 *
 * @see https://www.midjourney.com/app/jobs/3
 * @generated by generate-wallpapers-library
 */
export function AWallpaperFeaturingAStylizedIllustrationOfAF081b7e0f3c00428b85498ca19f7e7cdf0_3_Image() {
    return (
        <Image
            alt="a wallpaper featuring a stylized illustration of a f 081b7e0f-3c00-428b-8549-8ca19f7e7cdf-0"
            src={a_wallpaper_featuring_a_stylized_illustration_of_a_f_081b7e0f_3c00_428b_8549_8ca19f7e7cdf_0_3}
            draggable="false"
            placeholder="blur"
            style={{ objectFit: 'cover', width: '100%', height: '100%' }}
        />
    );
}
